%% 2D compositional-PHREEQC mineral comparison without bio-clogging
% Compare three sandstone mineral compositions while keeping flow,
% transport, microbial kinetics, and operating controls identical.
%
% Mineral weight percentages:
%   A: Bentheimer sandstone      - 0% calcite, 2% dolomite, 98% inert
%   B: Berea sandstone           - 2% calcite, 1% dolomite, 97% inert
%   C: Grey Berea sandstone      - 2% calcite, 0% dolomite, 98% inert

clearvars;
mrstModule add ad-core ad-blackoil ad-props deckformat mrst-gui upr test-suite spe10
mrstModule add compositional h2-biochem h2store

databaseSource = getenv('PHREEQC_DATABASE_FILE');
if isempty(strtrim(databaseSource))
    databaseSource = which('PHREEQC_Modified.DAT');
end
assert(~isempty(strtrim(databaseSource)) && isfile(databaseSource), ...
    ['PHREEQC_Modified.DAT was not found. Set the PHREEQC_DATABASE_FILE ', ...
     'environment variable to its absolute path.']);
databaseFile = stagePhreeqcDatabase(databaseSource);
numCycles = 1;

mineralCases = table( ...
    ["A"; "B"; "C"], ...
    ["Bentheimer sandstone"; "Berea sandstone"; "Grey Berea sandstone"], ...
    [0; 2; 2]./100, ...
    [2; 1; 0]./100, ...
    [98; 97; 98]./100, ...
    'VariableNames', {'Case', 'Rock', 'Calcite', 'Dolomite', 'Inert'});

%% Shared 2D aquifer, fluid, chemistry, and schedule
dataFile = fullfile(getDatasetPath('h2storage'), 'H2STORAGE_RS.DATA');
deck = readEclipseDeck(dataFile);
[~, ~, state0Bo, modelBo, scheduleBo] = ...
    modelForSimple2DAquifer(deck, 'numcycles', numCycles);
baseModel = convertBlackOilModelToCompositionalModel(modelBo);
baseState = convertBlackOilStateToCompositional(modelBo, state0Bo);

componentFluid = TableCompositionalMixture( ...
    {'Water', 'Hydrogen', 'CarbonDioxide', 'Methane', ...
     'HydrogenSulfide', 'AceticAcid'}, ...
    {'H2O', 'H2', 'CO2', 'C1', 'H2S', 'CH3COOH'});
reactionNames = { ...
    'MethanogenicArchae', ...
    'AcetogenicBacteria', ...
    'SulfateReducingBacteria'};
biomassNames = {'bactM', 'bactA', 'bactS'};
biochemFluid = TableBioChemMixture(reactionNames, biomassNames);

initialTemperature = 273.15 + 44.35;
initialPH = 7.2;
initialSO4 = 0.1;
initialHCO3 = 1.370e-3;
initialNaCl = 2.865;
waterDensity = 1000;
initialBiomass = [15, 15, 15];
composition = [0.8480, 1e-5, 1e-5, 0.1530, 0, 0];
composition = composition./sum(composition);
composition = repmat(composition, baseModel.G.cells.num, 1);
schedule = configureCompositionalSchedule(scheduleBo, initialTemperature);

resultTemplate = struct( ...
    'caseName', "", ...
    'rockName', "", ...
    'model', [], ...
    'schedule', [], ...
    'packedProblem', [], ...
    'wellSols', [], ...
    'states', [], ...
    'report', [], ...
    'elapsedSeconds', NaN, ...
    'h2ConsumedByReactionMoles', nan(1, 3), ...
    'timeDays', [], ...
    'h2LossPercent', [], ...
    'finalPH', [], ...
    'finalReactiveMineralMoles', nan(1, 2));
results = repmat(resultTemplate, height(mineralCases), 1);

%% Run the common original h2-biochem no-clogging baseline
fprintf('\nBaseline: original h2-biochem without bio-clogging\n');
originalModel = makeOriginalModel( ...
    baseModel, componentFluid, biochemFluid);
originalEos = SoreideWhitsonEos(originalModel.G, componentFluid, ...
    'msalt', initialNaCl, ...
    'pH', initialPH, ...
    'initial_NaCl', initialNaCl, ...
    'initial_SO4', initialSO4, ...
    'rho_water', waterDensity);
originalModel.EOSModel = originalEos;
originalModel.gravity = modelBo.gravity;
originalModel.outputFluxes = false;

originalState0 = initCompositionalStateBacteria( ...
    originalModel, baseState.pressure, initialTemperature, baseState.s, ...
    composition, initialBiomass, originalEos);
originalState0.tracerSO4 = repmat(initialSO4*waterDensity, ...
    originalModel.G.cells.num, 1);
originalState0.tracerHS = zeros(originalModel.G.cells.num, 1);
originalState0.h2sDissolvedLag = zeros(originalModel.G.cells.num, 1);

[originalSolver, ~] = setupOptimizedLinearSolver(originalModel, ...
    'complexityLevel', 'high', ...
    'solverTolerance', 1e-3, ...
    'maxNonlinIter', 10, ...
    'cprDamp', []);
originalProblem = packSimulationProblem( ...
    originalState0, originalModel, schedule, ...
    'H2_2D_NO_CLOG_ORIGINAL_SALINE', ...
    'NonLinearSolver', originalSolver);
timer = tic();
[ok, status] = simulatePackedProblem( ...
    originalProblem, 'continueOnError', false);
originalElapsedSeconds = toc(timer);
assert(ok, 'The original h2-biochem packed simulation failed: %s', ...
    status.Message);
[originalWellSols, originalStates, originalReport] = ...
    getPackedSimulatorOutput(originalProblem);
assert(numel(originalStates) == numel(schedule.step.val) && ...
    all(~cellfun(@isempty, originalStates)), ...
    'The original h2-biochem baseline did not complete all schedule steps.');

[originalH2Consumed, originalLossPercent] = consumptionAndLoss( ...
    originalStates, schedule, originalModel);
baseline = resultTemplate;
baseline.caseName = "Original";
baseline.rockName = "Original h2-biochem, no clogging";
baseline.model = originalModel;
baseline.schedule = schedule;
baseline.packedProblem = originalProblem;
baseline.wellSols = originalWellSols;
baseline.states = originalStates;
baseline.report = originalReport;
baseline.elapsedSeconds = originalElapsedSeconds;
baseline.h2ConsumedByReactionMoles = originalH2Consumed;
baseline.timeDays = cumsum(schedule.step.val(:))./day;
baseline.h2LossPercent = originalLossPercent;

%% Run no-clogging sequential compositional-PHREEQC cases
for caseNo = 1:height(mineralCases)
    fprintf('\nMineral case %s (%d/%d): %s\n', ...
        mineralCases.Case(caseNo), caseNo, height(mineralCases), ...
        mineralCases.Rock(caseNo));

    couplingOptions = makeCouplingOptions( ...
        databaseFile, waterDensity, initialNaCl, initialSO4, initialHCO3, ...
        mineralCases(caseNo, :));
    model = makePhreeqcModel( ...
        baseModel, componentFluid, biochemFluid, couplingOptions, ...
        databaseFile, initialPH);

    eos = SoreideWhitsonEos(model.G, componentFluid, ...
        'msalt', initialNaCl, ...
        'pH', initialPH, ...
        'initial_NaCl', initialNaCl, ...
        'initial_SO4', initialSO4, ...
        'rho_water', waterDensity);
    model.EOSModel = eos;
    model.gravity = modelBo.gravity;
    model.outputFluxes = false;

    state0 = initCompositionalStateBacteria( ...
        model, baseState.pressure, initialTemperature, baseState.s, ...
        composition, initialBiomass, eos);
    state0.tracerSO4 = repmat(initialSO4*waterDensity, ...
        model.G.cells.num, 1);
    state0.tracerHS = zeros(model.G.cells.num, 1);
    state0.tracerHCO3 = repmat(initialHCO3*waterDensity, ...
        model.G.cells.num, 1);
    state0.tracerCa = zeros(model.G.cells.num, 1);
    state0.tracerMg = zeros(model.G.cells.num, 1);
    state0.phreeqcHCO3Molality = repmat(initialHCO3, ...
        model.G.cells.num, 1);
    state0.phreeqcPE = 4*ones(model.G.cells.num, 1);
    state0 = initializeH2StoragePhreeqcCouplingState(model, state0);

    [nonlinearSolver, ~] = setupOptimizedLinearSolver(model, ...
        'complexityLevel', 'high', ...
        'solverTolerance', 1e-3, ...
        'maxNonlinIter', 10, ...
        'cprDamp', []);
    packedCaseName = sprintf( ...
        'H2_2D_NO_CLOG_PHREEQC_%s_SALINE_INERT', ...
        mineralCases.Case(caseNo));
    problem = packSimulationProblem( ...
        state0, model, schedule, packedCaseName, ...
        'NonLinearSolver', nonlinearSolver);
    timer = tic();
    [ok, status] = simulatePackedProblem( ...
        problem, 'continueOnError', false);
    elapsedSeconds = toc(timer);
    assert(ok, 'Packed mineral case %s failed: %s', ...
        mineralCases.Case(caseNo), status.Message);
    [wellSols, states, report] = getPackedSimulatorOutput(problem);
    assert(numel(states) == numel(schedule.step.val) && ...
        all(~cellfun(@isempty, states)), ...
        'Mineral case %s did not complete all schedule steps.', ...
        mineralCases.Case(caseNo));

    [h2Consumed, lossPercent] = consumptionAndLoss( ...
        states, schedule, model);
    finalState = states{end};

    results(caseNo).caseName = mineralCases.Case(caseNo);
    results(caseNo).rockName = mineralCases.Rock(caseNo);
    results(caseNo).model = model;
    results(caseNo).schedule = schedule;
    results(caseNo).packedProblem = problem;
    results(caseNo).wellSols = wellSols;
    results(caseNo).states = states;
    results(caseNo).report = report;
    results(caseNo).elapsedSeconds = elapsedSeconds;
    results(caseNo).h2ConsumedByReactionMoles = h2Consumed;
    results(caseNo).timeDays = cumsum(schedule.step.val(:))./day;
    results(caseNo).h2LossPercent = lossPercent;
    results(caseNo).finalPH = finalState.phreeqcPH;
    results(caseNo).finalReactiveMineralMoles = [ ...
        sum(finalState.phreeqcMineralCalcite), ...
        sum(finalState.phreeqcMineralDolomite)];
end

%% Comparison summaries
h2ByReaction = vertcat(results.h2ConsumedByReactionMoles);
finalMinerals = vertcat(results.finalReactiveMineralMoles);
meanFinalPH = arrayfun(@(entry) mean(entry.finalPH), results).';
allCaseNames = ["Original"; mineralCases.Case];
allRockNames = ["Original h2-biochem, no clogging"; mineralCases.Rock];
allH2ByReaction = [baseline.h2ConsumedByReactionMoles; h2ByReaction];
summary = table( ...
    allCaseNames, allRockNames, ...
    allH2ByReaction(:, 1), allH2ByReaction(:, 2), ...
    allH2ByReaction(:, 3), sum(allH2ByReaction, 2), ...
    [baseline.h2LossPercent(end); ...
        arrayfun(@(entry) entry.h2LossPercent(end), results).'], ...
    [NaN; meanFinalPH], ...
    [NaN; finalMinerals(:, 1)], ...
    [NaN; finalMinerals(:, 2)], ...
    [NaN; 100*mineralCases.Inert], ...
    [baseline.elapsedSeconds; [results.elapsedSeconds].'], ...
    'VariableNames', { ...
        'Case', 'Rock', 'H2_MET_mol', 'H2_ACE_mol', 'H2_SRB_mol', ...
        'H2_Total_mol', 'FinalH2LossPercent', 'MeanFinalPH', 'FinalCalcite_mol', ...
        'FinalDolomite_mol', 'InertRockWtPercent', 'ElapsedSeconds'});
disp(summary);

allResults = [baseline; results];
colors = paperColors(numel(allResults));

fig = paperFigure([24, 11], 'PHREEQC mineral comparison');
layout = tiledlayout(fig, 1, 2, 'TileSpacing', 'compact', 'Padding', 'compact');
ax = nexttile(layout);
bar(ax, categorical(allCaseNames, allCaseNames, 'Ordinal', true), ...
    allH2ByReaction, 'stacked');
ylabel(ax, 'Cumulative H_2 consumption (mol)');
title(ax, 'Microbial H_2 consumption');
legend(ax, {'MET', 'ACE', 'SRB'}, 'Location', 'best');
styleAxes(ax);

ax = nexttile(layout);
pHCounts = arrayfun(@(entry) numel(entry.finalPH), results).';
pHCase = repelem(mineralCases.Case, pHCounts);
boxchart(ax, categorical(pHCase), vertcat(results.finalPH));
ylabel(ax, 'Final pH');
title(ax, 'Cellwise final pH');
styleAxes(ax);
title(layout, 'Original h2-biochem baseline versus PHREEQC mineral cases');
paperExport(fig, 'minerals_2D_consumption_and_pH');

fig = paperFigure([20, 12], '2D H2 loss percentage');
ax = axes(fig);
hold(ax, 'on');
for caseNo = 1:numel(allResults)
    plot(ax, allResults(caseNo).timeDays, ...
        allResults(caseNo).h2LossPercent, 'LineWidth', 1.6, ...
        'Color', colors(caseNo, :), ...
        'DisplayName', char(string(allCaseNames(caseNo))));
end
xlabel(ax, 'Time (days)');
ylabel(ax, 'Cumulative H_2 loss (%)');
title(ax, '2D cumulative biological H_2 loss');
legend(ax, 'Location', 'best');
styleAxes(ax);
paperExport(fig, 'minerals_2D_H2_loss');

%% Local setup functions
function schedule = configureCompositionalSchedule(schedule, temperature)
for controlNo = 1:numel(schedule.control)
    schedule.control(controlNo).W.compi = [0, 1];
    if strcmp(schedule.control(controlNo).W.name, 'cushion') && controlNo < 11
        schedule.control(controlNo).W.components = ...
            [0, 0.1, 0.9, 0, 0, 0];
    else
        schedule.control(controlNo).W.components = ...
            [0, 0.95, 0.05, 0, 0, 0];
    end
    schedule.control(controlNo).W.T = temperature;
    schedule.control(controlNo).bc = [];
end
end

function [finalByReaction, lossPercent] = consumptionAndLoss( ...
        states, schedule, model)
nReactions = model.biochemFluid.nbioreact;
finalByReaction = zeros(1, nReactions);
cumulativeConsumed = zeros(numel(schedule.step.val), 1);
for reactionNo = 1:nReactions
    [~, cumulative] = computeH2Consumption( ...
        states, schedule, model, reactionNo);
    finalByReaction(reactionNo) = sum(cumulative(:, end));
    cumulativeConsumed = cumulativeConsumed + sum(cumulative, 1).';
end
cumulativeInjected = prescribedInjectedH2(schedule, model);
lossPercent = 100*cumulativeConsumed./cumulativeInjected;
end

function cumulativeInjected = prescribedInjectedH2(schedule, model)
names = model.EOSModel.CompositionalMixture.names;
h2Index = findComponentIndex(names, {'H2', 'Hydrogen'});
gasIndex = model.getVaporIndex();
increment = zeros(numel(schedule.step.val), 1);
for stepNo = 1:numel(schedule.step.val)
    wells = schedule.control(schedule.step.control(stepNo)).W;
    for wellNo = 1:numel(wells)
        well = wells(wellNo);
        if well.sign <= 0 || (isfield(well, 'status') && ~well.status)
            continue;
        end
        if strcmpi(well.type, 'grat')
            gasRate = well.val;
        elseif strcmpi(well.type, 'rate')
            gasRate = well.val*well.compi(gasIndex);
        else
            continue;
        end
        molarRate = gasRate*model.FacilityModel.pressure/ ...
            (8.314462618*model.FacilityModel.T);
        increment(stepNo) = increment(stepNo) + ...
            molarRate*well.components(h2Index)*schedule.step.val(stepNo);
    end
end
cumulativeInjected = cumsum(increment);
assert(all(cumulativeInjected > 0), ...
    'Every reported step must follow positive prescribed H2 injection.');
end

function index = findComponentIndex(names, aliases)
for aliasNo = 1:numel(aliases)
    index = find(strcmpi(names, aliases{aliasNo}), 1);
    if ~isempty(index)
        return;
    end
end
error('Required EOS component was not found: %s.', aliases{1});
end

function options = makeCouplingOptions( ...
        databaseFile, waterDensity, initialNaCl, initialSO4, ...
        initialHCO3, mineralCase)
% Add sulfate and bicarbonate countercharge to the NaCl brine.
% sequentialCompositionalPhreeqcBatchSize batches cells into a single
% IPhreeqcCOM RunString call (self-verified row/identifier checks in
% runSequentialCompositionalPhreeqcCoupling guard against a wrong
% cell-to-row mapping); 100000 puts every active cell in one call to
% minimise COM overhead, set it to 1 to fall back to one call per cell.
% sequentialCompositionalPhreeqcSteps is the number of PHREEQC kinetic
% sub-integrations per transport step (2 is a speed/accuracy compromise;
% raise towards 5 if the pH/DIC history changes noticeably).
initialNa = initialNaCl + 2*initialSO4 + initialHCO3;
options = struct( ...
    'databaseFile', databaseFile, ...
    'comProgId', 'IPhreeqcCOM.Object', ...
    'waterDensity', waterDensity, ...
    'Na', initialNa, ...
    'K', 0, ...
    'Ca', 0, ...
    'Mg', 0, ...
    'Cl', initialNaCl, ...
    'Si', 0, ...
    'dolomitePhase', 'Dolomite', ...
    'calcitePhase', 'Calcite', ...
    'brucitePhase', 'Brucite', ...
    'quartzPhase', 'Quartz', ...
    'dolomiteWtFraction', mineralCase.Dolomite, ...
    'calciteWtFraction', mineralCase.Calcite, ...
    'bruciteWtFraction', 0, ...
    'quartzWtFraction', 0, ...
    'inertWtFraction', mineralCase.Inert, ...
    'inertDensity', 2650, ...
    'initialDolomiteMoles', [], ...
    'initialCalciteMoles', [], ...
    'initialBruciteMoles', [], ...
    'initialQuartzMoles', [], ...
    'initialDolomiteMolality', [], ...
    'initialCalciteMolality', [], ...
    'initialBruciteMolality', [], ...
    'initialQuartzMolality', [], ...
    'sequentialCompositionalPhreeqcSteps', 2, ...
    'sequentialCompositionalPhreeqcBatchSize', 100000);
end

function model = makePhreeqcModel( ...
        baseModel, componentFluid, biochemFluid, couplingOptions, ...
        databaseFile, initialPH)
backend = DiagonalAutoDiffBackend('modifyOperators', true);
model = BiochemistryPhreeqcModel( ...
    baseModel.G, baseModel.rock, baseModel.fluid, ...
    componentFluid, biochemFluid, false, backend, ...
    'oil', true, ...
    'gas', true, ...
    'bacteriamodel', true, ...
    'bactDiffusion', false, ...
    'chemotaxisEffect', false, ...
    'molecularDiffusion', true, ...
    'molecularDispersion', true, ...
    'liquidPhase', 'O', ...
    'vaporPhase', 'G', ...
    'carbonateBuffer', true, ...
    'carbonateBufferPH', initialPH, ...
    'carbonateBufferPka1', 6.35, ...
    'phreeqcTimestepCoupling', true, ...
    'phreeqcBackend', 'sequential-compositional-phreeqc', ...
    'phreeqcDatabaseFile', databaseFile, ...
    'phreeqcComProgId', 'IPhreeqcCOM.Object', ...
    'phreeqcCouplingOptions', couplingOptions);
model.OutputStateFunctions{end + 1} = 'ComponentPhaseDensity';
end

function model = makeOriginalModel(baseModel, componentFluid, biochemFluid)
backend = DiagonalAutoDiffBackend('modifyOperators', true);
model = BiochemistryModel( ...
    baseModel.G, baseModel.rock, baseModel.fluid, ...
    componentFluid, biochemFluid, false, backend, ...
    'oil', true, ...
    'gas', true, ...
    'bacteriamodel', true, ...
    'bactDiffusion', false, ...
    'chemotaxisEffect', false, ...
    'molecularDiffusion', true, ...
    'molecularDispersion', true, ...
    'liquidPhase', 'O', ...
    'vaporPhase', 'G');
model.OutputStateFunctions{end + 1} = 'ComponentPhaseDensity';
end

function stagedFile = stagePhreeqcDatabase(sourceFile)
assert(ispc, ...
    'This example requires Windows and a registered IPhreeqcCOM server.');
assert(isfile(sourceFile), ...
    'PHREEQC database not found: %s', sourceFile);
stageDirectory = fullfile(tempdir, 'h2-biochem-phreeqc');
if ~isfolder(stageDirectory)
    [created, message] = mkdir(stageDirectory);
    assert(created, ...
        'Unable to create PHREEQC staging directory %s: %s', ...
        stageDirectory, message);
end
[~, name, extension] = fileparts(sourceFile);
stagedFile = fullfile(stageDirectory, [name, extension]);
[copied, message] = copyfile(sourceFile, stagedFile, 'f');
assert(copied && isfile(stagedFile), ...
    'Unable to stage PHREEQC database: %s', message);
end
