function comparison = exampleCompositionalBacterial1DPhreeqcMinerals(varargin)
% Compare original h2-biochem with three PHREEQC mineral cases in 1D.
%
% The test uses the 50-day injection period, no bio-clogging, and the same
% grid, flow controls, brine, biomass, and transport settings in all cases.

mrstModule add ad-core ad-props compositional deckformat h2-biochem

opt = struct( ...
    'phreeqcDatabaseFile', '', ...
    'gridCells', 50, ...
    'batchSize', 50);
opt = merge_options(opt, varargin{:});
opt.phreeqcDatabaseFile = resolvePhreeqcDatabaseFile(opt.phreeqcDatabaseFile);
validateattributes(opt.gridCells, {'numeric'}, ...
    {'scalar', 'integer', 'positive', 'finite'}, mfilename, 'gridCells');
validateattributes(opt.batchSize, {'numeric'}, ...
    {'scalar', 'integer', 'positive', 'finite'}, mfilename, 'batchSize');

mineralCases = table( ...
    ["A"; "B"; "C"], ...
    ["Bentheimer sandstone"; "Berea sandstone"; "Grey Berea sandstone"], ...
    [0; 2; 2]./100, ...
    [2; 1; 0]./100, ...
    [98; 97; 98]./100, ...
    'VariableNames', {'Case', 'Rock', 'Calcite', 'Dolomite', 'Inert'});

commonOptions = { ...
    'rate', 'highrate', ...
    'scheduleMode', 'complete', ...
    'gridCells', opt.gridCells, ...
    'domainLength', 50, ...
    'bacteriamodel', true, ...
    'bactDiffusion', false, ...
    'chemotaxisEffect', false, ...
    'molecularDiffusion', false, ...
    'molecularDispersion', false, ...
    'bioClogging', false, ...
    'carbonateBuffer', true, ...
    'carbonateBufferPH', 6.24, ...
    'initialHCO3', 1.370e-3, ...
    'initialOverallCO2', 0, ...
    'injectionCO2', 0};

template = struct( ...
    'name', "", ...
    'rock', "", ...
    'model', [], ...
    'schedule', [], ...
    'state0', [], ...
    'packedProblem', [], ...
    'wellSols', [], ...
    'states', [], ...
    'reports', [], ...
    'elapsedSeconds', NaN, ...
    'h2ConsumedByReactionMoles', nan(1, 3), ...
    'timeDays', [], ...
    'h2LossPercent', [], ...
    'xDimensionless', [], ...
    'spatialH2LossPercent', [], ...
    'finalPH', [], ...
    'finalReactiveMineralMoles', nan(1, 2));
comparison = repmat(template, 4, 1);

%% Original h2-biochem baseline
[~, model, schedule, state0] = setupH2StorageExampleWithSRB_benchmark( ...
    commonOptions{:}, ...
    'nbact0', 100, ... % 100*1e10 cells/m^3 = PHREEQC's 1e9 cells/kgw
    'phreeqcTimestepCoupling', false);
comparison(1) = runPackedCase( ...
    "Original", "Original h2-biochem, no clogging", ...
    model, schedule, state0, ...
    sprintf('H2_1D_NO_CLOG_ORIGINAL_MATCHED_INIT_INJECTION_%dCELLS', opt.gridCells));

%% Sequential compositional-PHREEQC mineral cases
for caseNo = 1:height(mineralCases)
    [~, model, schedule, state0] = setupH2StorageExampleWithSRB_benchmark( ...
        commonOptions{:}, ...
        'phreeqcTimestepCoupling', true, ...
        'phreeqcBackend', 'sequential-compositional-phreeqc', ...
        'phreeqcDatabaseFile', opt.phreeqcDatabaseFile, ...
        'phreeqcCalciteWtFraction', mineralCases.Calcite(caseNo), ...
        'phreeqcDolomiteWtFraction', mineralCases.Dolomite(caseNo), ...
        'phreeqcBruciteWtFraction', 0, ...
        'phreeqcQuartzWtFraction', 0, ...
        'phreeqcInertWtFraction', mineralCases.Inert(caseNo), ...
        'sequentialCompositionalPhreeqcBatchSize', ...
            min(opt.batchSize, opt.gridCells));
    assertMatchedInitialState(comparison(1), model, state0);
    packedName = sprintf('H2_1D_NO_CLOG_PHREEQC_%s_INJECTION_%dCELLS', ...
        mineralCases.Case(caseNo), opt.gridCells);
    comparison(caseNo + 1) = runPackedCase( ...
        mineralCases.Case(caseNo), mineralCases.Rock(caseNo), ...
        model, schedule, state0, packedName);
end

summary = makeSummary(comparison, mineralCases);
disp(summary);
plotComparison(comparison);
end

function assertMatchedInitialState(original, phreeqcModel, phreeqcState)
originalState = original.state0;
sharedFields = {'pressure', 'T', 'components', 'tracerSO4', 'tracerHCO3'};
for fieldNo = 1:numel(sharedFields)
    field = sharedFields{fieldNo};
    assert(isfield(originalState, field) && isfield(phreeqcState, field) && ...
        max(abs(value(originalState.(field)) - value(phreeqcState.(field))), ...
            [], 'all') < 1e-12, ...
        'Original and PHREEQC initial states differ in %s.', field);
end

originalPopulation = value(originalState.nbact).* ...
    original.model.biochemFluid.nbactMax;
opt = phreeqcModel.phreeqcCouplingOptions;
phreeqcPopulation = [ ...
    phreeqcState.sequentialCompositionalPhreeqcBiomassMET, ...
    phreeqcState.sequentialCompositionalPhreeqcBiomassACE, ...
    phreeqcState.sequentialCompositionalPhreeqcBiomassSRB].* ...
    opt.sequentialCompositionalPhreeqcBiomassMW./ ...
    opt.sequentialCompositionalPhreeqcCellMass.*opt.waterDensity;
assert(max(abs(originalPopulation - phreeqcPopulation), [], 'all') < 1, ...
    'Original and PHREEQC initial microbial populations are not matched.');
end

function result = runPackedCase(name, rock, model, schedule, state0, packedName)
fprintf('\nRunning %s: %s\n', name, rock);
solver = NonLinearSolver();
solver.maxTimestepCuts = 12;
problem = packSimulationProblem( ...
    state0, model, schedule, packedName, ...
    'NonLinearSolver', solver);
timer = tic();
[ok, status] = simulatePackedProblem(problem, 'continueOnError', false);
elapsedSeconds = toc(timer);
assert(ok, 'Packed case %s failed: %s', name, status.Message);
[wellSols, states, reports] = getPackedSimulatorOutput(problem);
assert(numel(states) == numel(schedule.step.val) && ...
    all(~cellfun(@isempty, states)), ...
    'Case %s did not complete all schedule steps.', name);

nReactions = model.biochemFluid.nbioreact;
h2Consumed = zeros(1, nReactions);
totalCumulativeConsumed = zeros(numel(schedule.step.val), 1);
finalSpatialConsumed = zeros(model.G.cells.num, 1);
for reactionNo = 1:nReactions
    [~, cumulative] = computeH2Consumption( ...
        states, schedule, model, reactionNo);
    h2Consumed(reactionNo) = sum(cumulative(:, end));
    totalCumulativeConsumed = totalCumulativeConsumed + ...
        sum(cumulative, 1).';
    finalSpatialConsumed = finalSpatialConsumed + cumulative(:, end);
end
timeDays = cumsum(schedule.step.val(:))./day;
cumulativeInjected = prescribedInjectedH2(schedule, model);
h2LossPercent = 100*totalCumulativeConsumed./cumulativeInjected;
x = model.G.cells.centroids(:, 1);
xDimensionless = (x - min(x))./max(max(x) - min(x), eps);

result = struct( ...
    'name', string(name), ...
    'rock', string(rock), ...
    'model', model, ...
    'schedule', schedule, ...
    'state0', state0, ...
    'packedProblem', problem, ...
    'wellSols', {wellSols}, ...
    'states', {states}, ...
    'reports', {reports}, ...
    'elapsedSeconds', elapsedSeconds, ...
    'h2ConsumedByReactionMoles', h2Consumed, ...
    'timeDays', timeDays, ...
    'h2LossPercent', h2LossPercent, ...
    'xDimensionless', xDimensionless, ...
    'spatialH2LossPercent', ...
        100*finalSpatialConsumed./cumulativeInjected(end), ...
    'finalPH', [], ...
    'finalReactiveMineralMoles', nan(1, 2));
if isa(model, 'BiochemistryPhreeqcModel') && ...
        model.isSequentialCompositionalPhreeqcBackend()
    finalState = states{end};
    result.finalPH = finalState.phreeqcPH;
    result.finalReactiveMineralMoles = [ ...
        sum(finalState.phreeqcMineralCalcite), ...
        sum(finalState.phreeqcMineralDolomite)];
end
end

function summary = makeSummary(comparison, mineralCases)
h2 = vertcat(comparison.h2ConsumedByReactionMoles);
meanPHValues = arrayfun(@(item) mean(item.finalPH), comparison(2:end));
meanPH = [NaN; reshape(meanPHValues, [], 1)];
finalH2LossPercent = reshape( ...
    arrayfun(@(item) item.h2LossPercent(end), comparison), [], 1);
minerals = vertcat(comparison.finalReactiveMineralMoles);
summary = table( ...
    vertcat(comparison.name), ...
    vertcat(comparison.rock), ...
    h2(:, 1), h2(:, 2), h2(:, 3), sum(h2, 2), ...
    finalH2LossPercent, ...
    meanPH, minerals(:, 1), minerals(:, 2), ...
    [NaN; 100*mineralCases.Inert], ...
    [comparison.elapsedSeconds].', ...
    'VariableNames', { ...
        'Case', 'Rock', 'H2_MET_mol', 'H2_ACE_mol', 'H2_SRB_mol', ...
        'H2_Total_mol', 'FinalH2LossPercent', 'MeanFinalPH', 'FinalCalcite_mol', ...
        'FinalDolomite_mol', 'InertRockWtPercent', 'ElapsedSeconds'});
end

function plotComparison(comparison)
names = vertcat(comparison.name);
h2 = vertcat(comparison.h2ConsumedByReactionMoles);
colors = paperColors(numel(comparison));

fig = paperFigure([24, 11], '1D original versus PHREEQC mineral cases');
layout = tiledlayout(fig, 1, 2, 'TileSpacing', 'compact', 'Padding', 'compact');
ax = nexttile(layout);
bar(ax, categorical(names, names, 'Ordinal', true), h2, 'stacked');
ylabel(ax, 'Cumulative H_2 consumption (mol)');
title(ax, 'Microbial H_2 consumption');
legend(ax, {'MET', 'ACE', 'SRB'}, 'Location', 'best');
styleAxes(ax);

ax = nexttile(layout);
phreeqc = comparison(2:end);
pHCounts = reshape(arrayfun(@(item) numel(item.finalPH), phreeqc), [], 1);
pHNames = repelem(vertcat(phreeqc.name), pHCounts);
boxchart(ax, categorical(pHNames), vertcat(phreeqc.finalPH));
ylabel(ax, 'Final pH');
title(ax, 'Cellwise final pH');
styleAxes(ax);
title(layout, '1D no-clogging injection comparison');
paperExport(fig, 'minerals_1D_consumption_and_pH');

fig = paperFigure([24, 11], '1D H2 loss percentage');
lossLayout = tiledlayout(fig, 1, 2, 'TileSpacing', 'compact', 'Padding', 'compact');
ax = nexttile(lossLayout);
hold(ax, 'on');
for caseNo = 1:numel(comparison)
    plot(ax, comparison(caseNo).timeDays, ...
        comparison(caseNo).h2LossPercent, 'LineWidth', 1.6, ...
        'Color', colors(caseNo, :), 'DisplayName', char(names(caseNo)));
end
xlabel(ax, 'Time (days)');
ylabel(ax, 'Cumulative H_2 loss (%)');
title(ax, 'Loss versus time');
legend(ax, 'Location', 'best');
styleAxes(ax);

ax = nexttile(lossLayout);
hold(ax, 'on');
for caseNo = 1:numel(comparison)
    plot(ax, comparison(caseNo).xDimensionless, ...
        comparison(caseNo).spatialH2LossPercent, 'LineWidth', 1.6, ...
        'Color', colors(caseNo, :));
end
xlabel(ax, 'Dimensionless distance, x/L');
ylabel(ax, 'Final cellwise H_2 loss (% of injected H_2)');
title(ax, 'Spatial loss distribution');
styleAxes(ax);
title(lossLayout, '1D cumulative biological H_2 loss');
paperExport(fig, 'minerals_1D_H2_loss');
end

function cumulativeInjected = prescribedInjectedH2(schedule, model)
names = model.EOSModel.CompositionalMixture.names;
h2Index = findComponentIndex(names, {'H2', 'Hydrogen'});
gasIndex = model.getVaporIndex();
increment = zeros(numel(schedule.step.val), 1);
for stepNo = 1:numel(schedule.step.val)
    wells = schedule.control(schedule.step.control(stepNo)).W;
    for wellNo = 1:numel(wells)
        well = wells(wellNo);
        if well.sign <= 0 || (isfield(well, 'status') && ~well.status)
            continue;
        end
        if strcmpi(well.type, 'grat')
            gasRate = well.val;
        elseif strcmpi(well.type, 'rate')
            gasRate = well.val*well.compi(gasIndex);
        else
            continue;
        end
        molarRate = gasRate*model.FacilityModel.pressure/ ...
            (8.314462618*model.FacilityModel.T);
        increment(stepNo) = increment(stepNo) + ...
            molarRate*well.components(h2Index)*schedule.step.val(stepNo);
    end
end
cumulativeInjected = cumsum(increment);
assert(all(cumulativeInjected > 0), ...
    'Every reported step must follow positive prescribed H2 injection.');
end

function index = findComponentIndex(names, aliases)
for aliasNo = 1:numel(aliases)
    index = find(strcmpi(names, aliases{aliasNo}), 1);
    if ~isempty(index)
        return;
    end
end
error('Required EOS component was not found: %s.', aliases{1});
end

function databaseFile = resolvePhreeqcDatabaseFile(databaseFile)
assert(ischar(databaseFile) || ...
    (isstring(databaseFile) && isscalar(databaseFile)), ...
    'phreeqcDatabaseFile must be a character vector or scalar string.');
databaseFile = char(databaseFile);
if isempty(strtrim(databaseFile))
    databaseFile = getenv('PHREEQC_DATABASE_FILE');
end
if isempty(strtrim(databaseFile))
    databaseFile = which('PHREEQC_Modified.DAT');
end
if isempty(strtrim(databaseFile)) || ~isfile(databaseFile)
    error('exampleCompositionalBacterial1DPhreeqcMinerals:MissingPhreeqcDatabase', ...
        ['PHREEQC_Modified.DAT was not found. Pass its absolute path using ', ...
         '''phreeqcDatabaseFile'', databaseFile, or set the ', ...
         'PHREEQC_DATABASE_FILE environment variable.']);
end
[~, name, extension] = fileparts(databaseFile);
assert(strcmpi([name, extension], 'PHREEQC_Modified.DAT'), ...
    'The database must be PHREEQC_Modified.DAT.');
end
