function db = bioChemFluidsStructs()
% Database of biochemical reaction parameters.
%
% RETURNS:
%   db - Struct array where each element describes one metabolic
%        reaction with the following fields:
%
%   metabolicReaction  - Name (e.g., 'MethanogenicArchae')
%   rH2, rsub          - Reactant names
%   pH2O, p2           - Product names
%   gamrH2, gamrsub,
%   gampH2O, gamp2     - Stoichiometric coefficients
%   Y_H2               - Yield scale used by reaction source terms
%   alphaH2, alphasub  - Half-saturation constants (mol/mol)
%   Psigrowthmax       - Maximum growth rate (1/s)
%   bbact              - Decay rate (1/s)
%   nbactMax           - Population scale used by reaction source terms
%   bactdiff           - Microbial diffusion coefficient (m^2/s)
%   xch_seuil          - Chemotaxis coefficient
%   Add new reactions by appending additional struct entries following
%   the same pattern.

db = [...
    struct(...
    'metabolicReaction', 'MethanogenicArchae', ...
    'rH2',                'H2', ...
    'rsub',               'CO2', ...
    'pH2O',               'H2O', ...
    'p2',                 'C1', ...
    'gamrH2',             -4, ...
    'gamrsub',            -1, ...
    'gampH2O',             2, ...
    'gamp2',               1, ...
    'Y_H2',               3.90875e11, ...
    'alphaH2',            3.6e-7, ...
    'alphasub',           1.98e-6, ...
    'Psigrowthmax',       1.338e-4, ...
    'bbact',              2.35148e-6, ...
    'nbactMax',           1.0e9,...
    'xch_seuil',          1.0e-7,...
    'bactdiff', 1.0e-9),...
    struct(...
    'metabolicReaction', 'AcetogenicBacteria', ...
    'rH2',                'H2', ...
    'rsub',               'CO2', ...
    'pH2O',               'H2O', ...
    'p2',                 'CH3COOH', ...
    'gamrH2',             -4, ...
    'gamrsub',            -2, ...
    'gampH2O',             2, ...
    'gamp2',               1, ...
    'Y_H2',               1.2e11, ...
    'alphaH2',            5.0e-6, ...
    'alphasub',           5.0e-6, ...
    'Psigrowthmax',       4.0e-5, ...
    'bbact',              1.5e-6, ...
    'nbactMax',           1.0e9,...
    'xch_seuil',          1.0e-7,...
    'bactdiff',           1.0e-12),...
    struct(...
    'metabolicReaction', 'SulfateReducingBacteria', ...
    'rH2',                'H2', ...
    'rsub',               'SO4', ...
    'pH2O',               'H2O', ...
    'p2',                 'H2S', ...
    'gamrH2',             -4, ...   % 5 moles H₂ consumed
    'gamrsub',            -1, ...   % 1 mole sulfate consumed
    'gampH2O',             4, ...   % 4 moles water produced
    'gamp2',               1, ...   % 1 mole H₂S produced
    'Y_H2',               3.0e10, ...
    'alphaH2',            2.0e-6, ...
    'alphasub',           2.0e-4, ...
    'Psigrowthmax',       2.0e-5, ...
    'bbact',              1.0e-6, ...
    'nbactMax',           1.0e9, ...
    'xch_seuil',          1.0e-7, ...
    'bactdiff',           1.0e-9)
    ];

    % To add new reactions: append a struct with metabolicReaction name and all required fields
    % (rH2, rsub, pH2O, p2, stoichiometric coefficients, kinetic parameters, bactdiff, xch_seuil)
end

%{
Copyright 2009-2026 SINTEF Digital, Mathematics & Cybernetics.

This file is part of The MATLAB Reservoir Simulation Toolbox (MRST).

MRST is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

MRST is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with MRST.  If not, see <http://www.gnu.org/licenses/>.
%}