function state = initializeH2StoragePhreeqcCouplingState(model, state)
% Initialize state carried by the post-timestep PHREEQC coupling.
%
% Mineral quantities are moles per grid cell. A PHREEQC initialization may
% provide per-cell mineral inventories through model.phreeqcCouplingOptions;
% otherwise configured rock fractions are used. This routine does not
% invoke PHREEQC.

assert(isa(model, 'BiochemistryPhreeqcModel'), ...
    'PHREEQC coupling requires a BiochemistryPhreeqcModel instance.');
assert(model.phreeqcTimestepCoupling, ...
    'PHREEQC timestep coupling is not enabled on this model.');
assert(isfield(state, 'tracerHCO3') && isfield(state, 'tracerCa') && ...
    isfield(state, 'tracerMg'), ...
    ['PHREEQC coupling initialization requires HCO3, Ca, and Mg ', ...
     'aqueous tracer states in mol/m3 liquid.']);

opt = getCouplingOptions(model);
nc = model.G.cells.num;

if ~isfield(state, 'phreeqcPH')
    state.phreeqcPH = repmat(model.carbonateBufferPH, nc, 1);
end
if ~isfield(state, 'phreeqcCarbonatePka1')
    state.phreeqcCarbonatePka1 = repmat(model.carbonateBufferPka1, nc, 1);
end
if ~isfield(state, 'phreeqcHCO3Molality')
    state.phreeqcHCO3Molality = max(value(state.tracerHCO3)./opt.waterDensity, 0);
end
if ~isfield(state, 'phreeqcFe2Molality')
    state.phreeqcFe2Molality = expandToCells(opt.Fe2, nc, ...
        'initial Fe(II) molality');
end
if ~isfield(state, 'phreeqcFe3Molality')
    state.phreeqcFe3Molality = expandToCells(opt.Fe3, nc, ...
        'initial Fe(III) molality');
end

waterMass = getWaterMass(model, state, opt.waterDensity);
if ~isempty(opt.initialDolomiteMoles)
    state.phreeqcMineralDolomite = expandToCells(opt.initialDolomiteMoles, nc, ...
        'initial Dolomite moles');
    state.phreeqcMineralCalcite = expandToCells(opt.initialCalciteMoles, nc, ...
        'initial Calcite moles');
    state.phreeqcMineralBrucite = expandToCells(opt.initialBruciteMoles, nc, ...
        'initial Brucite moles');
    state.phreeqcMineralQuartz = expandToCells(opt.initialQuartzMoles, nc, ...
        'initial Quartz moles');
elseif isempty(opt.initialDolomiteMolality)
    rhoRock = 1/(opt.inertWtFraction/opt.inertDensity + ...
        opt.quartzWtFraction/opt.quartzDensity + ...
        opt.dolomiteWtFraction/opt.dolomiteDensity + ...
        opt.calciteWtFraction/opt.calciteDensity + ...
        opt.bruciteWtFraction/opt.bruciteDensity);
    poreVolume = value(model.PVTPropertyFunctions.get(model, state, 'PoreVolume'));
    rockMass = max(model.G.cells.volumes - poreVolume, 0).*rhoRock;
    state.phreeqcMineralDolomite = opt.dolomiteWtFraction.*rockMass./opt.dolomiteMolarMass;
    state.phreeqcMineralCalcite = opt.calciteWtFraction.*rockMass./opt.calciteMolarMass;
    state.phreeqcMineralBrucite = opt.bruciteWtFraction.*rockMass./opt.bruciteMolarMass;
    state.phreeqcMineralQuartz = opt.quartzWtFraction.*rockMass./opt.quartzMolarMass;
else
    state.phreeqcMineralDolomite = opt.initialDolomiteMolality.*waterMass;
    state.phreeqcMineralCalcite = opt.initialCalciteMolality.*waterMass;
    state.phreeqcMineralBrucite = opt.initialBruciteMolality.*waterMass;
    state.phreeqcMineralQuartz = opt.initialQuartzMolality.*waterMass;
end

if model.isSequentialCompositionalPhreeqcBackend() || model.isSequentialH2BiochemPhreeqcBackend()
    % COM backends use the PHREEQC_Modified.DAT phase names. The optional
    % Mineral inventories are shared, whereas kinetic biomass remains
    % specific to the compositional split and separate from MRST's nbact state.
    state = initializeOptionalMineral(state, 'phreeqcMineralAnhydrite', ...
        opt.sequentialCompositionalPhreeqcInitialAnhydriteMoles, nc);
    state = initializeOptionalMineral(state, 'phreeqcMineralGoethite', ...
        opt.sequentialCompositionalPhreeqcInitialGoethiteMoles, nc);
    state = initializeOptionalMineral(state, 'phreeqcMineralPortlandite', ...
        opt.sequentialCompositionalPhreeqcInitialPortlanditeMoles, nc);
    state = initializeOptionalMineral(state, 'phreeqcMineralPyrite', ...
        opt.sequentialCompositionalPhreeqcInitialPyriteMoles, nc);
    state = initializeOptionalMineral(state, 'phreeqcMineralGypsum', ...
        opt.sequentialCompositionalPhreeqcInitialGypsumMoles, nc);

    if model.isSequentialCompositionalPhreeqcBackend()
        biomassMoles = opt.sequentialCompositionalPhreeqcN0*opt.sequentialCompositionalPhreeqcCellMass/opt.sequentialCompositionalPhreeqcBiomassMW;
        state.sequentialCompositionalPhreeqcBiomassMET = initialBiomass(state, ...
            'sequentialCompositionalPhreeqcBiomassMET', biomassMoles, nc);
        state.sequentialCompositionalPhreeqcBiomassACE = initialBiomass(state, ...
            'sequentialCompositionalPhreeqcBiomassACE', biomassMoles, nc);
        state.sequentialCompositionalPhreeqcBiomassSRB = initialBiomass(state, ...
            'sequentialCompositionalPhreeqcBiomassSRB', biomassMoles, nc);
    end
end
end

function waterMass = getWaterMass(model, state, rhoWater)
poreVolume = value(model.PVTPropertyFunctions.get(model, state, 'PoreVolume'));
s = value(state.s);
liquid = model.getLiquidIndex();
if iscell(s)
    sL = s{liquid};
else
    sL = s(:, liquid);
end
waterMass = poreVolume.*max(sL, 1e-12).*rhoWater;
end

function opt = getCouplingOptions(model)
opt = struct( ...
    'waterDensity', 1000, ...
    'Fe2', 0, ...
    'Fe3', 0, ...
    'dolomiteWtFraction', 0.02, ...
    'calciteWtFraction', 0, ...
    'bruciteWtFraction', 0, ...
    'quartzWtFraction', 0.98, ...
    'inertWtFraction', 0, ...
    'dolomiteDensity', 2840, ...
    'calciteDensity', 2710, ...
    'bruciteDensity', 2390, ...
    'quartzDensity', 2650, ...
    'inertDensity', 2650, ...
    'dolomiteMolarMass', 0.18440, ...
    'calciteMolarMass', 0.1000869, ...
    'bruciteMolarMass', 0.0583197, ...
    'quartzMolarMass', 0.060083, ...
    'initialDolomiteMoles', [], ...
    'initialCalciteMoles', [], ...
    'initialBruciteMoles', [], ...
    'initialQuartzMoles', [], ...
    'initialDolomiteMolality', [], ...
    'initialCalciteMolality', [], ...
    'initialBruciteMolality', [], ...
    'initialQuartzMolality', [], ...
    'sequentialCompositionalPhreeqcInitialAnhydriteMoles', 0, ...
    'sequentialCompositionalPhreeqcInitialGoethiteMoles', 0, ...
    'sequentialCompositionalPhreeqcInitialPortlanditeMoles', 0, ...
    'sequentialCompositionalPhreeqcInitialPyriteMoles', 0, ...
    'sequentialCompositionalPhreeqcInitialGypsumMoles', 0, ...
    'sequentialCompositionalPhreeqcN0', 1e9, ...
    'sequentialCompositionalPhreeqcCellMass', 1e-14, ...
    'sequentialCompositionalPhreeqcBiomassMW', 24.6);
names = fieldnames(opt);
configured = model.phreeqcCouplingOptions;
for i = 1:numel(names)
    name = names{i};
    if isfield(configured, name)
        opt.(name) = configured.(name);
    end
end
assert(all(cellfun(@isempty, {opt.initialDolomiteMoles, opt.initialCalciteMoles, ...
    opt.initialBruciteMoles, opt.initialQuartzMoles})) || ...
    all(~cellfun(@isempty, {opt.initialDolomiteMoles, opt.initialCalciteMoles, ...
    opt.initialBruciteMoles, opt.initialQuartzMoles})), ...
    'All four initial PHREEQC mineral inventories must be specified together.');
assert(all(cellfun(@isempty, {opt.initialDolomiteMolality, opt.initialCalciteMolality, ...
    opt.initialBruciteMolality, opt.initialQuartzMolality})) || ...
    all(~cellfun(@isempty, {opt.initialDolomiteMolality, opt.initialCalciteMolality, ...
    opt.initialBruciteMolality, opt.initialQuartzMolality})), ...
    'All four initial PHREEQC mineral molalities must be specified together.');
assert(isempty(opt.initialDolomiteMoles) || isempty(opt.initialDolomiteMolality), ...
    'Specify initial PHREEQC minerals as either moles or molalities, not both.');
assert(opt.dolomiteWtFraction + opt.calciteWtFraction + ...
    opt.bruciteWtFraction + opt.quartzWtFraction + ...
    opt.inertWtFraction <= 1, ...
    'Reactive and inert rock weight fractions must sum to no more than one.');
fractions = [opt.dolomiteWtFraction, opt.calciteWtFraction, ...
    opt.bruciteWtFraction, opt.quartzWtFraction, opt.inertWtFraction];
assert(all(isfinite(fractions) & fractions >= 0), ...
    'Reactive and inert rock weight fractions must be finite and non-negative.');
if isempty(opt.initialDolomiteMoles) && isempty(opt.initialDolomiteMolality)
    assert(sum(fractions) > 0, ...
        'PHREEQC fallback mineral weight fractions must not all be zero.');
end
end

function state = initializeOptionalMineral(state, name, configured, nc)
if ~isfield(state, name)
    state.(name) = expandToCells(configured, nc, name);
end
end

function values = initialBiomass(state, name, initial, nc)
if isfield(state, name)
    values = expandToCells(value(state.(name)), nc, name);
else
    values = repmat(initial, nc, 1);
end
end

function values = expandToCells(values, nc, name)
if isscalar(values)
    values = repmat(values, nc, 1);
else
    values = values(:);
    assert(numel(values) == nc, ...
        '%s must be scalar or contain one value per cell.', name);
end
assert(all(isfinite(values) & values >= 0), '%s must be finite and non-negative.', name);
end
