function state = runSequentialCompositionalPhreeqcCoupling(model, state, dt)
% Run the optional compositional PHREEQC split after convergence.
%
% This backend uses the PHREEQC_Modified.DAT IPhreeqcCOM input and
% SELECTED_OUTPUT convention. It is Windows-only: PHREEQC owns MET/ACE/SRB
% kinetics and its biomass state, while MRST retains flow and tracer
% transport. Its split conventions match the UGFACT H2Storage1D reference.
%
% Cells are processed through one persistent IPhreeqcCOM object and one
% PHREEQC_Modified.DAT database load per coupling invocation (actxserver
% activation and LoadDatabase are the expensive per-call operations).
% model.phreeqcCouplingOptions.sequentialCompositionalPhreeqcBatchSize
% (default 1, the behavior-safe/original setting) controls how many
% cells' PHREEQC keyword blocks are concatenated into each RunString
% call: with the default, this reduces exactly to the original one
% RunString-per-cell loop. With a batch size greater than 1, multiple
% cells are submitted in a single RunString call using unique local
% SOLUTION/GAS_PHASE/KINETICS/EQUILIBRIUM_PHASES numbers, and the
% returned SELECTED_OUTPUT rows are split back to their originating cells
% using a deterministic per-cell row count together with PHREEQC's "soln"
% and "sim" selected-output identifier columns (see selectedOutputBlock
% and splitBatchedSelectedOutput). That split is self-verified at runtime
% (row counts and identifier columns are checked for every batch); any
% mismatch raises H2Biochem:SequentialCompositionalPhreeqcBatchOutputMismatch
% instead of silently mis-attributing PHREEQC output to the wrong cell.

assert(isa(model, 'BiochemistryPhreeqcModel'), ...
    'compositional PHREEQC coupling requires a BiochemistryPhreeqcModel instance.');
assert(model.phreeqcTimestepCoupling && model.isSequentialCompositionalPhreeqcBackend(), ...
    'compositional PHREEQC IPhreeqcCOM timestep coupling is not enabled on this model.');
assert(ispc, ['compositional PHREEQC IPhreeqcCOM timestep coupling is available only on ', ...
    'Windows with a registered IPhreeqcCOM server.']);
validateattributes(dt, {'numeric'}, {'scalar', 'real', 'finite', 'positive'}, ...
    mfilename, 'dt');

opt = getCouplingOptions(model);
nc = model.G.cells.num;
validateCouplingOptions(opt, nc);
assert(exist('actxserver', 'file') == 2 || exist('actxserver', 'builtin') == 5, ...
    ['IPhreeqcCOM activation is unavailable. Install/register the Windows ', ...
     'IPhreeqcCOM server identified by phreeqcComProgId.']);

rhoWater = opt.waterDensity;
waterMass = getWaterMass(model, state, rhoWater);
assert(all(isfinite(waterMass) & waterMass > 0), ...
    'compositional PHREEQC coupling requires positive liquid water mass in every cell.');

state = initializeSequentialCompositionalPhreeqcState(state, opt, nc);
[state, firstCouplingStep] = ...
    applyReferenceFirstStepBiomassConvention(state, waterMass);
phase = getPhaseData(model, state, waterMass, rhoWater);
if firstCouplingStep
    % H2Storage1D equilibrates every water-containing cell on its first
    % bio-geochemical split, before applying the normal H2 activity mask.
    phase.activeCells = phase.sL >= 1e-3;
end
mineral = getMineralData(state, waterMass, nc);
state = storePhreeqcInputDiagnostics(state, phase);

results = repmat(emptyResult(), nc, 1);
% One IPhreeqcCOM object and one PHREEQC_Modified.DAT database load are
% reused for every cell (and every batch) in this coupling invocation;
% LoadDatabase/actxserver are the expensive operations, and IPhreeqcCOM
% supports repeated RunString calls on the same instance by design.
iph = openPhreeqcSession(opt);
cleanupIph = onCleanup(@() releasePhreeqcSession(iph));

preamble = buildPhreeqcPreamble(opt);
rowsPerCell = 1 + opt.sequentialCompositionalPhreeqcSteps;
batchSize = round(opt.sequentialCompositionalPhreeqcBatchSize);
firstBatch = true;
cellStart = 1;
while cellStart <= nc
    cellEnd = min(cellStart + batchSize - 1, nc);
    cellIdx = cellStart:cellEnd;
    input = buildPhreeqcBatchInput(preamble, opt, phase, mineral, ...
        state, cellIdx, dt);
    if firstBatch
        state.sequentialCompositionalPhreeqcInputCell1String = input;
        firstBatch = false;
    end
    output = runIPhreeqcCOMBatch(iph, input, cellIdx);
    cellOutputs = splitBatchedSelectedOutput(output, cellIdx, rowsPerCell);
    for k = 1:numel(cellIdx)
        results(cellIdx(k)) = parseSelectedOutput(cellOutputs{k}, cellIdx(k));
    end
    cellStart = cellEnd + 1;
end

state = auditElementBalance(state, opt, phase, ...
    mineral, results, waterMass);
state = updateStateFromResults(model, state, opt, phase, mineral, results, waterMass, dt);
end

function state = storePhreeqcInputDiagnostics(state, phase)
% Retain the exact mol/kg-water PHREEQC basis for diagnostics.
state.sequentialCompositionalPhreeqcInputWaterMass = phase.waterMass;
state.sequentialCompositionalPhreeqcInputH2Moles = phase.gasH2;
state.sequentialCompositionalPhreeqcInputCO2Moles = phase.gasCO2;
state.sequentialCompositionalPhreeqcInputCH4Moles = phase.gasCH4;
state.sequentialCompositionalPhreeqcInputH2SMoles = phase.gasH2S;
state.sequentialCompositionalPhreeqcInputGasVolumeLPerKg = phase.gasVolumeLPerKg;
state.sequentialCompositionalPhreeqcInputPH = phase.pH;
state.sequentialCompositionalPhreeqcInputC4 = phase.C4;
state.sequentialCompositionalPhreeqcInputS6 = phase.S6;
state.sequentialCompositionalPhreeqcInputCa = phase.Ca;
state.sequentialCompositionalPhreeqcInputMg = phase.Mg;
state.sequentialCompositionalPhreeqcInputActiveCells = phase.activeCells;
end

function opt = getCouplingOptions(model)
opt = struct( ...
    'databaseFile', model.phreeqcDatabaseFile, ...
    'comProgId', model.phreeqcComProgId, ...
    'waterDensity', 1000, ...
    'Na', 2.865, ...
    'K', 0, ...
    'Ca', 0.2857, ...
    'Mg', 0.1144, ...
    'Cl', 3.655, ...
    'Si', 9.723e-5, ...
    'Fe3', 0, ...
    'Fe2', 0, ...
    'sequentialCompositionalPhreeqcSteps', 5, ...
    'sequentialCompositionalPhreeqcBatchSize', 1, ...
    'sequentialCompositionalPhreeqcMuMET', 1.109, ...
    'sequentialCompositionalPhreeqcMuACE', 0.872, ...
    'sequentialCompositionalPhreeqcMuSRB', 1.048, ...
    'sequentialCompositionalPhreeqcBMET', 0.01109, ...
    'sequentialCompositionalPhreeqcBACE', 0.00872, ...
    'sequentialCompositionalPhreeqcBSRB', 0.01048, ...
    'sequentialCompositionalPhreeqcYMET', 0.03*4, ...
    'sequentialCompositionalPhreeqcYACE', 0.07*4, ...
    'sequentialCompositionalPhreeqcYSRB', 0.08*4, ...
    'sequentialCompositionalPhreeqcKDMET', 10e-6, ...
    'sequentialCompositionalPhreeqcKDACE', 2.5e-6, ...
    'sequentialCompositionalPhreeqcKDSRB', 2.9e-6, ...
    'sequentialCompositionalPhreeqcKAMET', 230e-6, ...
    'sequentialCompositionalPhreeqcKAACE', 115.5e-6, ...
    'sequentialCompositionalPhreeqcKASRB', 2751.5e-6, ...
    'sequentialCompositionalPhreeqcN0', 1e9, ...
    'sequentialCompositionalPhreeqcNmax', 1e13, ...
    'sequentialCompositionalPhreeqcCellMass', 1e-14, ...
    'sequentialCompositionalPhreeqcBiomassMW', 24.6, ...
    'sequentialCompositionalPhreeqcPinTDS', false, ...
    'phreeqcElementBalanceAbsoluteTolerance', 1e-7, ...
    'phreeqcElementBalanceRelativeTolerance', 1e-8);

configured = model.phreeqcCouplingOptions;
names = fieldnames(opt);
for i = 1:numel(names)
    name = names{i};
    if isfield(configured, name)
        opt.(name) = configured.(name);
    end
end
end

function validateCouplingOptions(opt, nc)
assert(ischar(opt.databaseFile) || ...
    (isstring(opt.databaseFile) && isscalar(opt.databaseFile)), ...
    'sequential-compositional-phreeqc databaseFile must be a character vector or scalar string.');
databaseFile = char(opt.databaseFile);
assert(~isempty(strtrim(databaseFile)) && isAbsolutePath(databaseFile), ...
    ['sequential-compositional-phreeqc requires an explicit absolute databaseFile path to ', ...
     'PHREEQC_Modified.DAT.']);
assert(isfile(databaseFile), ...
    'compositional PHREEQC database not found: %s', databaseFile);
[~, databaseName, extension] = fileparts(databaseFile);
assert(strcmpi(extension, '.dat') && contains(lower(databaseName), 'phreeqc_modified'), ...
    ['sequential-compositional-phreeqc requires PHREEQC_Modified.DAT, not a standard PHREEQC ', ...
     'Pitzer database: %s'], databaseFile);
assert(ischar(opt.comProgId) || (isstring(opt.comProgId) && isscalar(opt.comProgId)), ...
    'sequential-compositional-phreeqc comProgId must identify a registered IPhreeqcCOM server.');
assert(~isempty(strtrim(char(opt.comProgId))), ...
    'sequential-compositional-phreeqc comProgId must identify a registered IPhreeqcCOM server.');
validateattributes(opt.waterDensity, {'numeric'}, {'scalar', 'real', 'finite', 'positive'});
validateattributes(opt.sequentialCompositionalPhreeqcSteps, {'numeric'}, ...
    {'scalar', 'integer', 'finite', 'positive'});
validateattributes(opt.sequentialCompositionalPhreeqcBatchSize, {'numeric'}, ...
    {'scalar', 'integer', 'finite', 'positive'}, mfilename, ...
    'sequentialCompositionalPhreeqcBatchSize');

positive = {'sequentialCompositionalPhreeqcYMET', 'sequentialCompositionalPhreeqcYACE', 'sequentialCompositionalPhreeqcYSRB', ...
    'sequentialCompositionalPhreeqcKDMET', 'sequentialCompositionalPhreeqcKDACE', 'sequentialCompositionalPhreeqcKDSRB', ...
    'sequentialCompositionalPhreeqcKAMET', 'sequentialCompositionalPhreeqcKAACE', 'sequentialCompositionalPhreeqcKASRB', ...
    'sequentialCompositionalPhreeqcN0', 'sequentialCompositionalPhreeqcNmax', 'sequentialCompositionalPhreeqcCellMass', 'sequentialCompositionalPhreeqcBiomassMW'};
for i = 1:numel(positive)
    validateattributes(opt.(positive{i}), {'numeric'}, ...
        {'scalar', 'real', 'finite', 'positive'}, mfilename, positive{i});
end
nonnegative = {'sequentialCompositionalPhreeqcMuMET', 'sequentialCompositionalPhreeqcMuACE', 'sequentialCompositionalPhreeqcMuSRB', ...
    'sequentialCompositionalPhreeqcBMET', 'sequentialCompositionalPhreeqcBACE', 'sequentialCompositionalPhreeqcBSRB', ...
    'Na', 'K', 'Ca', 'Mg', 'Cl', 'Si'};
for i = 1:numel(nonnegative)
    validateattributes(opt.(nonnegative{i}), {'numeric'}, ...
        {'scalar', 'real', 'finite', 'nonnegative'}, mfilename, nonnegative{i});
end
for name = {'Fe3', 'Fe2'}
    values = opt.(name{1});
    validateattributes(values, {'numeric'}, ...
        {'vector', 'real', 'finite', 'nonnegative'}, mfilename, name{1});
    assert(isscalar(values) || numel(values) == nc, ...
        '%s must be scalar or contain one value per grid cell.', name{1});
end
assert(opt.sequentialCompositionalPhreeqcNmax >= opt.sequentialCompositionalPhreeqcN0, ...
    'sequentialCompositionalPhreeqcNmax must be at least sequentialCompositionalPhreeqcN0.');
validateattributes(opt.sequentialCompositionalPhreeqcPinTDS, {'logical'}, {'scalar'}, ...
    mfilename, 'sequentialCompositionalPhreeqcPinTDS');
end

function state = initializeSequentialCompositionalPhreeqcState(state, opt, nc)
% Stored biomass is mol/kg water and never aliases MRST's nbact field.
initialBiomass = opt.sequentialCompositionalPhreeqcN0*opt.sequentialCompositionalPhreeqcCellMass/opt.sequentialCompositionalPhreeqcBiomassMW;
biomassFields = {'sequentialCompositionalPhreeqcBiomassMET', 'sequentialCompositionalPhreeqcBiomassACE', ...
    'sequentialCompositionalPhreeqcBiomassSRB'};
for i = 1:numel(biomassFields)
    field = biomassFields{i};
    if isfield(state, field)
        values = asCellVector(value(state.(field)), nc, field);
        assert(all(isfinite(values) & values >= 0), ...
            '%s must be finite and non-negative.', field);
        state.(field) = values;
    else
        state.(field) = repmat(initialBiomass, nc, 1);
    end
end

mineralFields = {'phreeqcMineralCalcite', 'phreeqcMineralDolomite', ...
    'phreeqcMineralAnhydrite', 'phreeqcMineralQuartz', ...
    'phreeqcMineralGoethite', 'phreeqcMineralBrucite', ...
    'phreeqcMineralPortlandite', 'phreeqcMineralPyrite', ...
    'phreeqcMineralGypsum'};
for i = 1:numel(mineralFields)
    field = mineralFields{i};
    if ~isfield(state, field)
        state.(field) = zeros(nc, 1);
    end
end
end

function [state, firstCouplingStep] = ...
        applyReferenceFirstStepBiomassConvention(state, waterMass)
% H2Storage1D initializes Solution.*_Biomass in mol/kgw, but its first
% buildPhreeqcStrings call divides those values by cell water mass as if
% they were mol/cell. Subsequent calls use PHREEQC output stored in
% mol/cell and are unit-consistent. Retain that first-step convention for
% compatibility with the reference result.
flag = 'sequentialCompositionalPhreeqcFirstStepBiomassConventionApplied';
if isfield(state, flag) && state.(flag)
    firstCouplingStep = false;
    return;
end
firstCouplingStep = true;
fields = {'sequentialCompositionalPhreeqcBiomassMET', 'sequentialCompositionalPhreeqcBiomassACE', ...
    'sequentialCompositionalPhreeqcBiomassSRB'};
for i = 1:numel(fields)
    field = fields{i};
    state.(field) = state.(field)./waterMass;
end
state.(flag) = true;
end

function phase = getPhaseData(model, state, waterMass, rhoWater)
nc = model.G.cells.num;
phase = struct();
phase.waterMass = waterMass;
phase.temperature = asCellVector(value(state.T), nc, 'temperature');
phase.pressureAtm = asCellVector(value(state.pressure)./101325, nc, 'pressure');
phase.pH = getStateVector(state, 'phreeqcPH', nc, model.carbonateBufferPH);
phase.Na = optionVector(model.phreeqcCouplingOptions, 'Na', 2.865, nc);
phase.K = optionVector(model.phreeqcCouplingOptions, 'K', 0, nc);
phase.Cl = optionVector(model.phreeqcCouplingOptions, 'Cl', 3.655, nc);
phase.Si = optionVector(model.phreeqcCouplingOptions, 'Si', 9.723e-5, nc);
initialFe3 = optionVector(model.phreeqcCouplingOptions, 'Fe3', 0, nc);
initialFe2 = optionVector(model.phreeqcCouplingOptions, 'Fe2', 0, nc);
phase.Fe3 = max(getStateVector(state, 'phreeqcFe3Molality', nc, initialFe3), 0);
phase.Fe2 = max(getStateVector(state, 'phreeqcFe2Molality', nc, initialFe2), 0);
phase.Ca = max(getStateVector(state, 'tracerCa', nc, 0)./rhoWater, 0);
phase.Mg = max(getStateVector(state, 'tracerMg', nc, 0)./rhoWater, 0);
phase.S6 = max(getStateVector(state, 'tracerSO4', nc, 0)./rhoWater, 0);
phase.S2 = max(getStateVector(state, 'tracerHS', nc, 0)./rhoWater, 0);

componentMoles = getEOSComponentMoles(model, state);
phase.componentMoles = componentMoles;
[phase.rhoL, phase.rhoV, phase.sL, phase.sV] = getPhaseProperties(model, state);
poreVolume = asCellVector(value(model.PVTPropertyFunctions.get( ...
    model, state, 'PoreVolume')), nc, 'pore volume');
phase.gasVolumeLPerKg = max(poreVolume.*phase.sV.*1000./waterMass, 1e-12);
phase.gasVolumeL = max(poreVolume.*phase.sV.*1000, 1e-6);
phase.ZV = asCellVector(value(state.Z_V), nc, 'gas compressibility factor');
phase.gasTemperature = phase.temperature;

names = model.EOSModel.CompositionalMixture.names;
% compositional PHREEQC's GAS_PHASE inventory is its total component inventory per kg
% water, rather than only the EOS vapor-phase portion. This gives PHREEQC
% the complete volatile inventory to repartition; supplying only y*Sg
% would silently discard pre-existing dissolved gas at every split.
phase.gasH2 = getComponentMoles(componentMoles, names, {'H2', 'Hydrogen'});
phase.gasCO2 = getComponentMoles(componentMoles, names, {'CO2', 'CarbonDioxide'});
phase.gasCH4 = getComponentMoles(componentMoles, names, {'C1', 'CH4', 'Methane'});
phase.gasH2S = getComponentMoles(componentMoles, names, {'H2S', 'HydrogenSulfide'});
phase.gasN2 = getComponentMoles(componentMoles, names, {'N2', 'Nitrogen'}, false);
components = value(state.components);
% Match compositional PHREEQC's component cleanup before the PHREEQC gas inventory is
% constructed.
phase.gasH2 = zeroTraceComponent(phase.gasH2, components, names, {'H2', 'Hydrogen'});
phase.gasCO2 = zeroTraceComponent(phase.gasCO2, components, names, {'CO2', 'CarbonDioxide'});
phase.gasCH4 = zeroTraceComponent(phase.gasCH4, components, names, {'C1', 'CH4', 'Methane'});
phase.gasH2S = zeroTraceComponent(phase.gasH2S, components, names, {'H2S', 'HydrogenSulfide'});
phase.gasN2 = zeroTraceComponent(phase.gasN2, components, names, {'N2', 'Nitrogen'});
phase.totalH2 = phase.gasH2;
iH2 = findComponent(names, {'H2', 'Hydrogen'});
phase.activeCells = components(:, iH2) > 1e-3 & phase.sL >= 1e-3;
phase.partialH2 = gasPartialPressure(phase.gasH2, phase);
phase.partialCO2 = gasPartialPressure(phase.gasCO2, phase);
phase.partialCH4 = gasPartialPressure(phase.gasCH4, phase);
phase.partialH2S = gasPartialPressure(phase.gasH2S, phase);
phase.partialN2 = gasPartialPressure(phase.gasN2, phase);

% tracerHCO3 carries nonvolatile C(4). EOS CO2 is supplied separately in
% GAS_PHASE_MODIFY, exactly as in compositional PHREEQC; adding dissolved EOS CO2 here
% would count the same carbon inventory twice.
phase.C4 = max(getStateVector(state, 'tracerHCO3', nc, 0)./rhoWater, 0);
phase.Acetate = max(getStateVector(state, 'sequentialCompositionalPhreeqcAcetate', nc, 0), 0);

% Brine TDS (g/kgw, used as a g/L proxy) computed from the same
% non-volatile ion inventory PHREEQC's SOLUTION block is given, before
% GAS_PHASE injects the EOS's total (dissolved+vapor) component
% inventory. Unlike PHREEQC's own RHO/SOLN_VOL-based TDS -- which is
% evaluated after GAS_PHASE re-equilibration and so picks up that
% injected gas mass -- this is independent of the gas split, matching
% the "true brine" TDS the empirical rate-suppression curve was meant to
% respond to. Only used when sequentialCompositionalPhreeqcPinTDS is set.
ionMolarMassGPerMol = struct('Na', 22.99, 'K', 39.10, 'Ca', 40.08, ...
    'Mg', 24.31, 'Cl', 35.45, 'Si', 28.09, 'S6', 96.06, 'S2', 33.07, ...
    'Fe3', 55.85, 'Fe2', 55.85, 'Acetate', 59.05, 'C4', 61.02);
phase.brineTDS = phase.Na.*ionMolarMassGPerMol.Na + phase.K.*ionMolarMassGPerMol.K + ...
    phase.Ca.*ionMolarMassGPerMol.Ca + phase.Mg.*ionMolarMassGPerMol.Mg + ...
    phase.Cl.*ionMolarMassGPerMol.Cl + phase.Si.*ionMolarMassGPerMol.Si + ...
    phase.S6.*ionMolarMassGPerMol.S6 + phase.S2.*ionMolarMassGPerMol.S2 + ...
    phase.Fe3.*ionMolarMassGPerMol.Fe3 + phase.Fe2.*ionMolarMassGPerMol.Fe2 + ...
    phase.Acetate.*ionMolarMassGPerMol.Acetate + phase.C4.*ionMolarMassGPerMol.C4;
end

function mineral = getMineralData(state, waterMass, nc)
mineral = struct();
mineral.calcite = getStateVector(state, 'phreeqcMineralCalcite', nc, 0)./waterMass;
mineral.dolomite = getStateVector(state, 'phreeqcMineralDolomite', nc, 0)./waterMass;
mineral.anhydrite = getStateVector(state, 'phreeqcMineralAnhydrite', nc, 0)./waterMass;
mineral.quartz = getStateVector(state, 'phreeqcMineralQuartz', nc, 0)./waterMass;
mineral.goethite = getStateVector(state, 'phreeqcMineralGoethite', nc, 0)./waterMass;
mineral.brucite = getStateVector(state, 'phreeqcMineralBrucite', nc, 0)./waterMass;
mineral.portlandite = getStateVector(state, 'phreeqcMineralPortlandite', nc, 0)./waterMass;
mineral.pyrite = getStateVector(state, 'phreeqcMineralPyrite', nc, 0)./waterMass;
mineral.gypsum = getStateVector(state, 'phreeqcMineralGypsum', nc, 0)./waterMass;
end

function input = buildPhreeqcBatchInput(preamble, opt, phase, mineral, ...
        state, cellIdx, dt)
% Build one RunString payload for a batch of cells: the shared preamble
% (SELECTED_OUTPUT/USER_PUNCH/KNOBS/RATES, cell-independent) followed by
% one self-contained SOLUTION/GAS_PHASE/KINETICS/EQUILIBRIUM_PHASES/USE
% block per cell. Each cell in the batch is assigned a unique local
% PHREEQC entity number (1..numel(cellIdx)), matching the standard
% IPhreeqcCOM convention for concatenating independent batch reactions
% (as used by PhreeqcRM-style multi-cell couplings) so that PHREEQC does
% not overwrite one cell's SOLUTION/KINETICS/EQUILIBRIUM_PHASES/GAS_PHASE
% definitions with another's within the same RunString call. With the
% default batch size of 1 this reduces to the original single-cell input
% (entity number 1), byte-for-byte identical apart from the -sim/-soln
% selected-output identifier columns enabled in selectedOutputBlock.
blocks = cell(1, numel(cellIdx));
for i = 1:numel(cellIdx)
    blocks{i} = buildPhreeqcCellBlock(opt, phase, mineral, state, ...
        cellIdx(i), dt, i);
end
input = [preamble, blocks{:}];
end

function preamble = buildPhreeqcPreamble(opt)
% Build the SELECTED_OUTPUT/USER_PUNCH/KNOBS/RATES header shared by every
% cell processed in this coupling invocation. This text depends only on
% opt (not on cellNo/dt/state), so it is built once and prefixed to every
% RunString batch instead of being repeated per cell.
maxBiomass = opt.sequentialCompositionalPhreeqcNmax*opt.sequentialCompositionalPhreeqcCellMass/opt.sequentialCompositionalPhreeqcBiomassMW;
minBiomass = opt.sequentialCompositionalPhreeqcN0*opt.sequentialCompositionalPhreeqcCellMass/opt.sequentialCompositionalPhreeqcBiomassMW;
preamble = sprintf([ ...
    '%s' ...
    'KNOBS\n' ...
    '-iterations 800\n' ...
    '-step_size 30\n' ...
    '-convergence_tolerance 1e-10\n' ...
    '%s' ...
    'END\n'], ...
    selectedOutputBlock(), ...
    buildRates(opt, minBiomass, maxBiomass));
end

function block = buildPhreeqcCellBlock(opt, phase, mineral, state, cellNo, dt, localId)
% Build the SOLUTION/GAS_PHASE/KINETICS/EQUILIBRIUM_PHASES/USE block for a
% single cell, numbered with localId (the cell's position within its
% RunString batch, 1..batchSize) rather than a hardcoded "1", so that
% multiple cells' blocks can be concatenated safely into one batch.
biomassMET = state.sequentialCompositionalPhreeqcBiomassMET(cellNo);
biomassACE = state.sequentialCompositionalPhreeqcBiomassACE(cellNo);
biomassSRB = state.sequentialCompositionalPhreeqcBiomassSRB(cellNo);
maxBiomass = opt.sequentialCompositionalPhreeqcNmax*opt.sequentialCompositionalPhreeqcCellMass/opt.sequentialCompositionalPhreeqcBiomassMW;
if phase.activeCells(cellNo)
    h2Available = max(phase.totalH2(cellNo)./phase.waterMass(cellNo), 0);
else
    h2Available = 0;
end
if opt.sequentialCompositionalPhreeqcPinTDS
    tdsParmLine = sprintf('-parm %.15g\n', phase.brineTDS(cellNo));
else
    tdsParmLine = '';
end

block = sprintf([ ...
    'SOLUTION %d\n' ...
    '-pressure %.15g\n' ...
    '-temp %.15g\n' ...
    'pH %.15g #charge\n' ...
    'units mol/kgw\n' ...
    'K %.15g\n' ...
    'Na %.15g\n' ...
    'Mg %.15g\n' ...
    'Ca %.15g\n' ...
    'Cl %.15g\n' ...
    'Carbonate(4) %.15g\n' ...
    'Sulfate(6) %.15g\n' ...
    'Sulfide(-2) %.15g\n' ...
    'Fe_tri %.15g\n' ...
    'Fe_di %.15g\n' ...
    'Si %.15g\n' ...
    'Acetate %.15g\n' ...
    '-water 1\n' ...
    'END\n' ...
    'GAS_PHASE %d\n' ...
    '-pressure %.15g\n' ...
    '-temp %.15g\n' ...
    '-fixed_volume\n' ...
    '-volume %.15g\n' ...
    'H2(g) %.15g\n' ...
    'redoxCarbonateO2(g) %.15g\n' ...
    'redoxCH4(g) %.15g\n' ...
    'redoxH2S(g) %.15g\n' ...
    'N2(g) %.15g\n' ...
    'GAS_PHASE_MODIFY %d\n' ...
    '-type 1\n' ...
    '-total_p %.15g\n' ...
    '-volume %.15g\n' ...
    '-component H2(g)\n' ...
    '-moles %.15g\n' ...
    '-component redoxCH4(g)\n' ...
    '-moles %.15g\n' ...
    '-component redoxCarbonateO2(g)\n' ...
    '-moles %.15g\n' ...
    '-component redoxH2S(g)\n' ...
    '-moles %.15g\n' ...
    '-component N2(g)\n' ...
    '-moles %.15g\n' ...
    'END\n' ...
    'INCREMENTAL_REACTIONS true\n' ...
    'KINETICS %d\n' ...
    'Biomass_SRB\n' ...
    '-formula H 0\n' ...
    '-M0 %.15g\n' ...
    'Biomass_MET\n' ...
    '-formula H 0\n' ...
    '-M0 %.15g\n' ...
    'Biomass_ACE\n' ...
    '-formula H 0\n' ...
    '-M0 %.15g\n' ...
    'MET\n' ...
    '-M %.15g moles\n' ...
    '%s' ...
    '-formula HCarbonateO3 -0.25 H2 -1 H+ -0.25 MethaneH4 0.25 H2O 0.75\n' ...
    'SRB\n' ...
    '-M %.15g moles\n' ...
    '%s' ...
    '-formula SulfateO4 -0.25 H2 -1 H+ -0.25 HSulfide 0.25 H2O 1\n' ...
    'ACE\n' ...
    '-M %.15g moles\n' ...
    '%s' ...
    '-formula HCarbonateO3 -0.5 H2 -1 H+ -0.25 Acetate 0.25 H2O 1\n' ...
    '-step %.15g in %d steps\n' ...
    '-bad_step_max 800\n' ...
    'END\n' ...
    'EQUILIBRIUM_PHASES %d\n' ...
    'redoxCalcite 0 %.15g\n' ...
    'redoxDolomite 0 %.15g\n' ...
    'redoxAnhydrite 0 %.15g\n' ...
    'Quartz 0 %.15g\n' ...
    'redoxGoethite 0 %.15g\n' ...
    'redoxPyrite 0 %.15g\n' ...
    'Brucite 0 %.15g\n' ...
    'Portlandite 0 %.15g\n' ...
    'redoxGypsum 0 %.15g\n' ...
    'END\n' ...
    'USE solution %d\n' ...
    'USE kinetics %d\n' ...
    'USE equilibrium_phases %d\n' ...
    'USE gas_phase %d\n' ...
    ], ...
    localId, ...
    phase.pressureAtm(cellNo), phase.temperature(cellNo) - 273.15, phase.pH(cellNo), ...
    phase.K(cellNo), phase.Na(cellNo), phase.Mg(cellNo), phase.Ca(cellNo), ...
    phase.Cl(cellNo), phase.C4(cellNo), phase.S6(cellNo), phase.S2(cellNo), ...
    phase.Fe3(cellNo), phase.Fe2(cellNo), phase.Si(cellNo), phase.Acetate(cellNo), ...
    localId, ...
    phase.pressureAtm(cellNo), phase.temperature(cellNo) - 273.15, ...
    phase.gasVolumeLPerKg(cellNo), ...
    phase.partialH2(cellNo), phase.partialCO2(cellNo), ...
    phase.partialCH4(cellNo), phase.partialH2S(cellNo), phase.partialN2(cellNo), ...
    localId, ...
    phase.pressureAtm(cellNo), phase.gasVolumeLPerKg(cellNo), ...
    phase.gasH2(cellNo)./phase.waterMass(cellNo), ...
    phase.gasCH4(cellNo)./phase.waterMass(cellNo), ...
    phase.gasCO2(cellNo)./phase.waterMass(cellNo), ...
    phase.gasH2S(cellNo)./phase.waterMass(cellNo), ...
    phase.gasN2(cellNo)./phase.waterMass(cellNo), ...
    localId, ...
    min(biomassSRB, maxBiomass), min(biomassMET, maxBiomass), ...
    min(biomassACE, maxBiomass), ...
    h2Available, tdsParmLine, h2Available, tdsParmLine, h2Available, tdsParmLine, ...
    dt, opt.sequentialCompositionalPhreeqcSteps, ...
    localId, ...
    mineral.calcite(cellNo), mineral.dolomite(cellNo), mineral.anhydrite(cellNo), ...
    mineral.quartz(cellNo), mineral.goethite(cellNo), mineral.pyrite(cellNo), ...
    mineral.brucite(cellNo), mineral.portlandite(cellNo), mineral.gypsum(cellNo), ...
    localId, localId, localId, localId);
end

function rates = buildRates(opt, minBiomass, maxBiomass)
if opt.sequentialCompositionalPhreeqcPinTDS
    tdsLine = sprintf('101 TDS = PARM(1)\n');
else
    tdsLine = sprintf('101 TDS = (RHO - TOT("water")/SOLN_VOL)*1e3\n');
end
rates = sprintf([ ...
    'RATES\n' ...
    'MET\n' ...
    '-start\n' ...
    '20 rate = %.15g/86400/%.15g*kin("Biomass_MET")*mol("H2")/(%.15g+mol("H2"))*tot("Carbonate(4)")/(%.15g+tot("Carbonate(4)"))\n' ...
    '30 if (TC<45) then rate = -rate * (TC-10)*(TC+10-2*45)/(45-10)^2\n' ...
    '40 if (TC>=45) then rate = -rate * (TC-122)*(TC+122-2*45)/(45-122)^2\n' ...
    '50 if (-LA("H+")<7.7) then rate = -rate * (-LA("H+")-4.1)*(-LA("H+")+4.1-2*7.7)/(7.7-4.1)^2\n' ...
    '60 if (-LA("H+")>=7.7) then rate = -rate * (-LA("H+")-10.2)*(-LA("H+")+10.2-2*7.7)/(7.7-10.2)^2\n' ...
    '70 if (-LA("H+")>=10.2) then rate = 0\n' ...
    '80 if (-LA("H+")<=4.1) then rate = 0\n' ...
    '90 if (TC<=10) then rate = 0\n' ...
    '100 if (TC>=122) then rate = 0\n' ...
    '%s' ...
    '102 if (TDS>=50) then rate = rate * (TDS-2*50+300)*(300-TDS)/(300-50)^2\n' ...
    '103 if (TDS>300) then rate = 0\n' ...
    '110 put(rate,1)\n' ...
    '120 moles = rate*TIME\n' ...
    '200 SAVE moles\n' ...
    '-end\n' ...
    'SRB\n' ...
    '-start\n' ...
    '20 rate = %.15g/86400/%.15g*kin("Biomass_SRB")*mol("H2")/(%.15g+mol("H2"))*mol("SulfateO4-2")/(%.15g+mol("SulfateO4-2"))\n' ...
    '30 if (TC<48) then rate = -rate * (TC-10)*(TC+10-2*48)/(48-10)^2\n' ...
    '40 if (TC>=48) then rate = -rate * (TC-113)*(TC+113-2*48)/(48-113)^2\n' ...
    '50 if (-LA("H+")<7.01) then rate = -rate * (-LA("H+")-1)*(-LA("H+")+1-2*7.01)/(7.01-1)^2\n' ...
    '60 if (-LA("H+")>=7.01) then rate = -rate * (-LA("H+")-11.5)*(-LA("H+")+11.5-2*7.01)/(7.01-11.5)^2\n' ...
    '70 if (-LA("H+")>=11.5) then rate = 0\n' ...
    '80 if (-LA("H+")<=1) then rate = 0\n' ...
    '90 if (TC<=10) then rate = 0\n' ...
    '100 if (TC>=113) then rate = 0\n' ...
    '%s' ...
    '102 if (TDS>=50) then rate = rate * (TDS-2*50+300)*(300-TDS)/(300-50)^2\n' ...
    '103 if (TDS>300) then rate = 0\n' ...
    '110 put(rate,2)\n' ...
    '120 moles = rate*TIME\n' ...
    '200 SAVE moles\n' ...
    '-end\n' ...
    'ACE\n' ...
    '-start\n' ...
    '20 rate = %.15g/86400/%.15g*kin("Biomass_ACE")*mol("H2")/(%.15g+mol("H2"))*tot("Carbonate(4)")/(%.15g+tot("Carbonate(4)"))\n' ...
    '30 if (TC<38) then rate = -rate * (TC-25)*(TC+25-2*38)/(38-25)^2\n' ...
    '40 if (TC>=38) then rate = -rate * (TC-72)*(TC+72-2*38)/(72-38)^2\n' ...
    '50 if (-LA("H+")<7.04) then rate = -rate * (-LA("H+")-3.6)*(-LA("H+")+3.6-2*7.04)/(7.04-3.6)^2\n' ...
    '60 if (-LA("H+")>=7.04) then rate = -rate * (-LA("H+")-9.5)*(-LA("H+")+9.5-2*7.04)/(7.04-9.5)^2\n' ...
    '70 if (-LA("H+")>=9.5) then rate = 0\n' ...
    '80 if (-LA("H+")<=3.6) then rate = 0\n' ...
    '90 if (TC<=25) then rate = 0\n' ...
    '100 if (TC>=72) then rate = 0\n' ...
    '%s' ...
    '102 if (TDS>=50) then rate = rate * (TDS-2*50+300)*(300-TDS)/(300-50)^2\n' ...
    '103 if (TDS>300) then rate = 0\n' ...
    '110 put(rate,3)\n' ...
    '120 moles = rate*TIME\n' ...
    '200 SAVE moles\n' ...
    '-end\n' ...
    'Biomass_MET\n' ...
    '-start\n' ...
    '20 rate = get(1)\n' ...
    '30 Y = %.15g\n' ...
    '40 b = %.15g/86400\n' ...
    '50 rate = Y*rate-b*M\n' ...
    '60 moles = -rate*TIME\n' ...
    '70 N = (M-moles)*%.15g\n' ...
    '80 if (M-moles)<%.15g then moles = M-%.15g\n' ...
    '90 if (N>=%.15g) then moles = M-%.15g\n' ...
    '200 SAVE moles\n' ...
    '-end\n' ...
    'Biomass_SRB\n' ...
    '-start\n' ...
    '20 rate = get(2)\n' ...
    '30 Y = %.15g\n' ...
    '40 b = %.15g/86400\n' ...
    '50 rate = Y*rate-b*M\n' ...
    '60 moles = -rate*TIME\n' ...
    '70 N = (M-moles)*%.15g\n' ...
    '80 if (M-moles)<%.15g then moles = M-%.15g\n' ...
    '90 if (N>=%.15g) then moles = M-%.15g\n' ...
    '200 SAVE moles\n' ...
    '-end\n' ...
    'Biomass_ACE\n' ...
    '-start\n' ...
    '20 rate = get(3)\n' ...
    '30 Y = %.15g\n' ...
    '40 b = %.15g/86400\n' ...
    '50 rate = Y*rate-b*M\n' ...
    '60 moles = -rate*TIME\n' ...
    '70 N = (M-moles)*%.15g\n' ...
    '80 if (M-moles)<%.15g then moles = M-%.15g\n' ...
    '90 if (N>=%.15g) then moles = M-%.15g\n' ...
    '200 SAVE moles\n' ...
    '-end\n'], ...
    opt.sequentialCompositionalPhreeqcMuMET, opt.sequentialCompositionalPhreeqcYMET, opt.sequentialCompositionalPhreeqcKDMET, opt.sequentialCompositionalPhreeqcKAMET, tdsLine, ...
    opt.sequentialCompositionalPhreeqcMuSRB, opt.sequentialCompositionalPhreeqcYSRB, opt.sequentialCompositionalPhreeqcKDSRB, opt.sequentialCompositionalPhreeqcKASRB, tdsLine, ...
    opt.sequentialCompositionalPhreeqcMuACE, opt.sequentialCompositionalPhreeqcYACE, opt.sequentialCompositionalPhreeqcKDACE, opt.sequentialCompositionalPhreeqcKAACE, tdsLine, ...
    opt.sequentialCompositionalPhreeqcYMET, opt.sequentialCompositionalPhreeqcBMET, opt.sequentialCompositionalPhreeqcBiomassMW/opt.sequentialCompositionalPhreeqcCellMass, ...
    minBiomass, minBiomass, opt.sequentialCompositionalPhreeqcNmax, maxBiomass, ...
    opt.sequentialCompositionalPhreeqcYSRB, opt.sequentialCompositionalPhreeqcBSRB, opt.sequentialCompositionalPhreeqcBiomassMW/opt.sequentialCompositionalPhreeqcCellMass, ...
    minBiomass, minBiomass, opt.sequentialCompositionalPhreeqcNmax, maxBiomass, ...
    opt.sequentialCompositionalPhreeqcYACE, opt.sequentialCompositionalPhreeqcBACE, opt.sequentialCompositionalPhreeqcBiomassMW/opt.sequentialCompositionalPhreeqcCellMass, ...
    minBiomass, minBiomass, opt.sequentialCompositionalPhreeqcNmax, maxBiomass);
end

function block = selectedOutputBlock()
% Keep the compositional PHREEQC selected-output order and custom pseudo-species intact.
% -sim/-soln are enabled (unlike the reference H2Storage1D convention) as
% diagnostics. PHREEQC may assign an internal working-solution number to
% kinetics rows, so only the simulation number is used as a cell boundary.
block = sprintf([ ...
    'USER_PUNCH\n' ...
    '-headings MET_RATE ACE_RATE SRB_RATE TDS CO3-2 HCO3- TOT_CO2 Dissolved_CO2 Z_Factor act("Ca+2") act("CO3-2") act(CaHCO3+) Ca+2 CaHCO3+ REACTIVE_SYSTEM_H\n' ...
    '-start\n' ...
    '20 rate1 = get(1)\n' ...
    '30 Punch rate1\n' ...
    '40 rate2 = get(3)\n' ...
    '50 Punch rate2\n' ...
    '60 rate3 = get(2)\n' ...
    '70 Punch rate3\n' ...
    '80 Punch (RHO - TOT("water")/SOLN_VOL)*1e3\n' ...
    '90 Punch MOL("CarbonateO3-2")\n' ...
    '91 Punch MOL("HCarbonateO3-")\n' ...
    '92 Punch GAS("redoxCarbonateO2(g)") + MOL("CarbonateO2")\n' ...
    '93 Punch TOT("Carbonate(4)") - MOL("CarbonateO3-2") - MOL("HCarbonateO3-") - MOL("CaHCarbonateO3+")\n' ...
    '94 Punch GAS_P*GAS_VM/TK/0.082057366080960\n' ...
    '95 Punch act("Ca+2")\n' ...
    '96 Punch act("CarbonateO3-2")\n' ...
    '97 Punch act("CaHCarbonateO3+")\n' ...
    '98 Punch mol("Ca+2")\n' ...
    '99 Punch mol("CaHCarbonateO3+")\n' ...
    '100 totalh = SYS("H", counth, nameh$, typeh$, molesh)\n' ...
    '110 reactiveh = 0\n' ...
    '120 FOR i = 1 TO counth\n' ...
    '130 IF (typeh$(i) <> "aq" OR nameh$(i) <> "H2O") THEN reactiveh = reactiveh + molesh(i)\n' ...
    '140 NEXT i\n' ...
    '150 reactiveh = reactiveh + 2*(TOT("water") - 1)*1000/GFW("H2O")\n' ...
    '160 Punch reactiveh\n' ...
    '-end\n' ...
    'SELECTED_OUTPUT\n' ...
    '-sim true\n' ...
    '-step true\n' ...
    '-soln true\n' ...
    '-pH true\n' ...
    '-molalities H2 N2 CarbonateO2 MethaneH4 H2Sulfide\n' ...
    '-state false\n' ...
    '-water true\n' ...
    '-time true\n' ...
    '-gases H2(g) redoxCarbonateO2(g) redoxCH4(g) redoxH2S(g) N2(g)\n' ...
    '-distance false\n' ...
    '-equilibrium_phases redoxCalcite redoxAnhydrite redoxGypsum redoxDolomite redoxGoethite redoxPyrite Brucite Portlandite Quartz\n' ...
    '-kinetic_reactants Biomass_SRB Biomass_MET Biomass_ACE\n' ...
    '-total Carbonate(4) Sulfate(6) Ca Mg Fe_di Fe_tri K Na Cl Acetate Sulfide(-2) Si\n' ...
    '-saturation_indices redoxCalcite Brucite Portlandite redoxAnhydrite redoxDolomite Quartz redoxH2S(g)\n' ...
    'END\n']);
end

function iph = openPhreeqcSession(opt)
% Create and initialize the single IPhreeqcCOM object reused for every
% cell (and every batch) in one coupling invocation. actxserver activation
% and LoadDatabase are the expensive, one-time-per-invocation operations;
% RunString/GetSelectedOutputArray are designed to be called repeatedly on
% the same loaded instance.
try
    iph = actxserver(char(opt.comProgId));
catch ME
    error('H2Biochem:SequentialCompositionalPhreeqcActivation', ...
        'IPhreeqcCOM activation failed for "%s":\n%s', ...
        char(opt.comProgId), ME.message);
end
try
    loadStatus = iph.LoadDatabase(char(opt.databaseFile));
    if loadStatus ~= 0
        message = getPhreeqcError(iph);
        releasePhreeqcSession(iph);
        error('H2Biochem:SequentialCompositionalPhreeqcDatabase', ...
            'PHREEQC database load failed:\n%s', message);
    end
catch ME
    if startsWith(ME.identifier, 'H2Biochem:SequentialCompositionalPhreeqc')
        rethrow(ME);
    end
    message = getPhreeqcError(iph);
    releasePhreeqcSession(iph);
    error('H2Biochem:SequentialCompositionalPhreeqcDatabase', ...
        'PHREEQC database load failed:\n%s\nPHREEQC message:\n%s', ME.message, message);
end
end

function releasePhreeqcSession(iph)
% Release the persistent IPhreeqcCOM object. Called both on normal
% completion (via onCleanup in runSequentialCompositionalPhreeqcCoupling)
% and on early error paths in openPhreeqcSession.
try
    delete(iph);
catch
end
end

function output = runIPhreeqcCOMBatch(iph, input, cellIdx)
% Run one RunString call covering the cells in cellIdx on the persistent,
% already-loaded IPhreeqcCOM session iph.
cellRangeText = cellRangeDescription(cellIdx);
try
    status = iph.RunString(input);
    if status ~= 0
        error('H2Biochem:SequentialCompositionalPhreeqcRun', ...
            'PHREEQC failed for cells %s:\n%s', cellRangeText, getPhreeqcError(iph));
    end
    output = iph.GetSelectedOutputArray;
    if isempty(output)
        error('H2Biochem:SequentialCompositionalPhreeqcOutput', ...
            'PHREEQC returned no selected output for cells %s:\n%s', ...
            cellRangeText, getPhreeqcError(iph));
    end
catch ME
    if startsWith(ME.identifier, 'H2Biochem:SequentialCompositionalPhreeqc')
        rethrow(ME);
    end
    phreeqcMessage = getPhreeqcError(iph);
    error('H2Biochem:SequentialCompositionalPhreeqcRun', ...
        'IPhreeqcCOM failed for cells %s:\n%s\nPHREEQC message:\n%s', ...
        cellRangeText, ME.message, phreeqcMessage);
end
end

function text = cellRangeDescription(cellIdx)
if isscalar(cellIdx)
    text = sprintf('%d', cellIdx);
else
    text = sprintf('%d-%d', cellIdx(1), cellIdx(end));
end
end

function cellRaw = splitBatchedSelectedOutput(raw, cellIdx, rowsPerCell)
% Split one RunString batch's combined SELECTED_OUTPUT array back into the
% per-cell raw arrays expected by parseSelectedOutput.
%
% Splitting relies on two self-checked pieces of information:
%   1. A fixed, a-priori known row count with one negative-step initial
%      SOLUTION row and a positive-step KINETICS block per cell.
%   2. Every KINETICS block must repeat the same PHREEQC "step" sequence.
%
% PHREEQC resets "sim" for independent USE blocks, can report internal
% working-solution identifiers in "soln", and may change where initial rows
% appear for larger batches. The step sign reliably distinguishes initial
% rows from kinetics rows; execution order is preserved within each group.
% Reducing sequentialCompositionalPhreeqcBatchSize to 1 (the default)
% always avoids this code path entirely.
cellRangeText = cellRangeDescription(cellIdx);
assert(iscell(raw) && size(raw, 1) >= 2 && size(raw, 2) >= 1, ...
    ['PHREEQC batched selected output for cells %s does not follow the required ', ...
     'compositional PHREEQC GetSelectedOutputArray schema.'], cellRangeText);
headers = normalizeHeaders(raw(1, :));
nCells = numel(cellIdx);
expectedRows = nCells*rowsPerCell;
dataRows = raw(2:end, :);
if size(dataRows, 1) ~= expectedRows
    error('H2Biochem:SequentialCompositionalPhreeqcBatchOutputMismatch', ...
        ['PHREEQC batched selected output for cells %s returned %d rows, expected %d ', ...
         '(%d cells x %d rows/cell). Set sequentialCompositionalPhreeqcBatchSize to 1 to ', ...
         'disable multi-cell RunString batching.'], ...
        cellRangeText, size(dataRows, 1), expectedRows, nCells, rowsPerCell);
end
stepColumn = find(ismember(headers, {'step'}), 1);
if isempty(stepColumn)
    error('H2Biochem:SequentialCompositionalPhreeqcBatchOutputMismatch', ...
        ['PHREEQC batched selected output for cells %s is missing the "step" ', ...
         'identifier columns required to split multi-cell RunString batches. Set ', ...
         'sequentialCompositionalPhreeqcBatchSize to 1 to disable batching.'], cellRangeText);
end
stepValues = cellfun(@toNumericScalar, dataRows(:, stepColumn));

cellRaw = cell(1, nCells);
kineticsRowsPerCell = rowsPerCell - 1;
initialRows = find(stepValues < 0);
allKineticsRows = find(stepValues >= 0);
if numel(initialRows) ~= nCells || ...
        numel(allKineticsRows) ~= nCells*kineticsRowsPerCell
    error('H2Biochem:SequentialCompositionalPhreeqcBatchOutputMismatch', ...
        ['PHREEQC batched selected output for cells %s contains %d initial ', ...
         'rows and %d kinetics rows; expected %d and %d. Observed steps: %s.'], ...
        cellRangeText, numel(initialRows), numel(allKineticsRows), nCells, ...
        nCells*kineticsRowsPerCell, summarizeNumericVector(stepValues));
end
referenceSteps = stepValues(allKineticsRows(1:kineticsRowsPerCell));
if numel(unique(referenceSteps)) ~= kineticsRowsPerCell
    error('H2Biochem:SequentialCompositionalPhreeqcBatchOutputMismatch', ...
        ['PHREEQC batched selected output for cells %s has an invalid first ', ...
         'kinetics-step sequence: %s.'], ...
        cellRangeText, mat2str(referenceSteps(:).'));
end
for i = 1:nCells
    kineticsRows = allKineticsRows((i - 1)*kineticsRowsPerCell + ...
        (1:kineticsRowsPerCell));
    cellSteps = stepValues(kineticsRows);
    if ~isequal(cellSteps, referenceSteps)
        error('H2Biochem:SequentialCompositionalPhreeqcBatchOutputMismatch', ...
            ['PHREEQC batched selected output for cells %s misattributed rows: cell %d ', ...
             'does not repeat the expected selected-output step sequence. Observed steps: ', ...
             '%s; expected: %s. Set ', ...
             'sequentialCompositionalPhreeqcBatchSize to 1 to disable batching.'], ...
            cellRangeText, cellIdx(i), mat2str(cellSteps(:).'), ...
            mat2str(referenceSteps(:).'));
    end
    cellRaw{i} = [raw(1, :); dataRows(initialRows(i), :); ...
        dataRows(kineticsRows, :)];
end
end

function text = summarizeNumericVector(values)
maxShown = 30;
values = values(:).';
if numel(values) <= maxShown
    text = mat2str(values);
else
    text = sprintf('%s ... %s (%d values)', ...
        mat2str(values(1:maxShown/2)), ...
        mat2str(values(end-maxShown/2+1:end)), numel(values));
end
end

function value = toNumericScalar(entry)
if ischar(entry) || (isstring(entry) && isscalar(entry))
    value = str2double(entry);
else
    value = entry;
end
end

function message = getPhreeqcError(iph)
try
    message = char(iph.GetErrorString());
catch
    message = 'No PHREEQC error string was available from IPhreeqcCOM.';
end
if isempty(strtrim(message))
    message = 'IPhreeqcCOM did not provide an error message.';
end
end

function result = parseSelectedOutput(raw, cellNo)
assert(iscell(raw) && size(raw, 1) >= 2 && size(raw, 2) >= 1, ...
    ['PHREEQC selected output in cell %d does not follow the required ', ...
     'compositional PHREEQC GetSelectedOutputArray schema.'], cellNo);
headers = normalizeHeaders(raw(1, :));
values = selectedOutputValues(raw(2:end, :), cellNo);
assert(all(isfinite(values(:))), ...
    'PHREEQC selected output contains non-finite values in cell %d.', cellNo);

result = emptyResult();
result.pH = finalValue(values, headers, {'ph'}, cellNo);
% IPhreeqcCOM versions differ in whether selected molality headers retain
% PHREEQC's "m_" prefix. Accept both representations of the unchanged
% compositional PHREEQC selected-output schema.
result.aqH2 = finalValue(values, headers, {'mh2', 'mh2molkgw', 'h2'}, cellNo);
result.aqN2 = finalValue(values, headers, {'mn2', 'mn2molkgw', 'n2'}, cellNo);
result.aqCO2 = finalValue(values, headers, ...
    {'mcarbonateo2', 'mcarbonateo2molkgw', 'carbonateo2'}, cellNo);
result.aqCH4 = finalValue(values, ...
    headers, {'mmethaneh4', 'mmethaneh4molkgw', 'methaneh4'}, cellNo);
result.aqH2S = finalValue(values, ...
    headers, {'mh2sulfide', 'mh2sulfidemolkgw', 'h2sulfide'}, cellNo);
result.water = finalValue(values, headers, {'water', 'massh2o'}, cellNo);
result.gasH2 = finalValue(values, headers, {'gh2g', 'h2g'}, cellNo);
result.gasCO2 = finalValue(values, headers, ...
    {'gredoxcarbonateo2g', 'redoxcarbonateo2g'}, cellNo);
result.gasCH4 = finalValue(values, headers, {'gredoxch4g', 'redoxch4g'}, cellNo);
result.gasH2S = finalValue(values, headers, {'gredoxh2sg', 'redoxh2sg'}, cellNo);
result.gasN2 = finalValue(values, headers, {'gn2g', 'n2g'}, cellNo);
result.calcite = finalValue(values, headers, ...
    {'redoxcalcite', 'equiredoxcalcite'}, cellNo);
result.anhydrite = finalValue(values, headers, ...
    {'redoxanhydrite', 'equiredoxanhydrite'}, cellNo);
result.gypsum = finalValue(values, headers, ...
    {'redoxgypsum', 'equiredoxgypsum'}, cellNo);
result.dolomite = finalValue(values, headers, ...
    {'redoxdolomite', 'equiredoxdolomite'}, cellNo);
result.goethite = finalValue(values, headers, ...
    {'redoxgoethite', 'equiredoxgoethite'}, cellNo);
result.pyrite = finalValue(values, headers, ...
    {'redoxpyrite', 'equiredoxpyrite'}, cellNo);
result.brucite = finalValue(values, headers, {'brucite', 'equibrucite'}, cellNo);
result.portlandite = finalValue(values, headers, ...
    {'portlandite', 'equiportlandite'}, cellNo);
result.quartz = finalValue(values, headers, {'quartz', 'equiquartz'}, cellNo);
result.biomassSRB = finalValue(values, headers, {'kbiomasssrb', 'biomasssrb'}, cellNo);
result.biomassMET = finalValue(values, headers, {'kbiomassmet', 'biomassmet'}, cellNo);
result.biomassACE = finalValue(values, headers, {'kbiomassace', 'biomassace'}, cellNo);
result.totalCarbon = finalValue(values, headers, ...
    {'carbonate4', 'carbonate4molkgw'}, cellNo);
result.sulfate = finalValue(values, headers, ...
    {'sulfate6', 'sulfate6molkgw'}, cellNo);
result.ca = finalValue(values, headers, {'ca', 'camolkgw'}, cellNo);
result.mg = finalValue(values, headers, {'mg', 'mgmolkgw'}, cellNo);
result.acetate = finalValue(values, headers, ...
    {'acetate', 'acetatemolkgw'}, cellNo);
result.sulfide = finalValue(values, headers, ...
    {'sulfide2', 'sulfide2molkgw'}, cellNo);
result.fe2 = finalValue(values, headers, {'fedi', 'fedimolkgw'}, cellNo);
result.fe3 = finalValue(values, headers, {'fetri', 'fetrimolkgw'}, cellNo);
result.hco3 = finalValue(values, headers, {'hco3'}, cellNo);
hydrogen = selectedValue(values, headers, {'reactivesystemh'}, cellNo);
assert(numel(hydrogen) >= 2, ...
    ['PHREEQC selected output in cell %d lacks distinct initial and final ', ...
     'reactive-hydrogen inventories.'], cellNo);
result.initialSystemHydrogen = hydrogen(1);
result.systemHydrogen = hydrogen(end);

time = selectedValue(values, headers, {'time'}, cellNo);
% The first row is emitted before KINETICS solely for the element audit.
% Preserve the original rate integration by averaging kinetics rows only.
kineticsRows = 2:numel(time);
assert(~isempty(kineticsRows), ...
    'PHREEQC selected output in cell %d contains no kinetics rows.', cellNo);
rateMET = selectedValue(values, headers, {'metrate'}, cellNo);
rateACE = selectedValue(values, headers, {'acerate'}, cellNo);
rateSRB = selectedValue(values, headers, {'srbrate'}, cellNo);
result.rateMET = timeAverage(time(kineticsRows), rateMET(kineticsRows));
result.rateACE = timeAverage(time(kineticsRows), rateACE(kineticsRows));
result.rateSRB = timeAverage(time(kineticsRows), rateSRB(kineticsRows));
% Diagnostic only (not fed back into the reaction rates themselves): the
% same USER_PUNCH-computed TDS the RATES blocks evaluate internally as
% TDS/PARM(1), time-averaged the same way as the reaction rates, so the
% pinned vs RHO-based TDS actually used by PHREEQC can be inspected via
% state.sequentialCompositionalPhreeqcTDS instead of assumed.
tds = selectedValue(values, headers, {'tds'}, cellNo);
result.tds = timeAverage(time(kineticsRows), tds(kineticsRows));
end

function state = auditElementBalance(state, options, phase, mineral, result, waterMass)
input = elementReservoirs(phase, mineral, waterMass);
output = outputElementReservoirs(result, waterMass);
[inputInventory, elements] = computePhreeqcElementInventory(input);
outputInventory = computePhreeqcElementInventory(output);
% The first row is the interpreted SOLUTION (selected output is installed
% before SOLUTION); add the explicitly supplied gas/mineral hydrogen.
inputInventory(:, 1) = inputInventory(:, 1) + ...
    reshape([result.initialSystemHydrogen], [], 1).*waterMass;
outputInventory(:, 1) = reshape([result.systemHydrogen], [], 1).*waterMass;
state = checkPhreeqcElementBalance(state, inputInventory, outputInventory, ...
    elements, options, 'sequential-compositional-phreeqc');
end

function r = elementReservoirs(phase, mineral, waterMass)
r = struct('hydrogen', zeros(size(waterMass)), ...
    'c4', phase.C4.*waterMass, 'acetate', phase.Acetate.*waterMass, ...
    's6', phase.S6.*waterMass, 's2', phase.S2.*waterMass, ...
    'ca', phase.Ca.*waterMass, 'mg', phase.Mg.*waterMass, ...
    'fe2', phase.Fe2.*waterMass, 'fe3', phase.Fe3.*waterMass, ...
    'gasH2', phase.gasH2, 'gasCO2', phase.gasCO2, ...
    'gasCH4', phase.gasCH4, 'gasH2S', phase.gasH2S, ...
    'calcite', mineral.calcite.*waterMass, ...
    'dolomite', mineral.dolomite.*waterMass, ...
    'anhydrite', mineral.anhydrite.*waterMass, ...
    'gypsum', mineral.gypsum.*waterMass, ...
    'goethite', mineral.goethite.*waterMass, ...
    'pyrite', mineral.pyrite.*waterMass, ...
    'brucite', mineral.brucite.*waterMass, ...
    'portlandite', mineral.portlandite.*waterMass);
end

function r = outputElementReservoirs(result, waterMass)
column = @(field) reshape([result.(field)], [], 1).*waterMass;
aqueous = @(field) reshape([result.(field)], [], 1).* ...
    reshape([result.water], [], 1).*waterMass;
r = struct('hydrogen', zeros(size(waterMass)), ...
    'c4', aqueous('totalCarbon'), 'acetate', aqueous('acetate'), ...
    's6', aqueous('sulfate'), 's2', aqueous('sulfide'), ...
    'ca', aqueous('ca'), 'mg', aqueous('mg'), ...
    'fe2', aqueous('fe2'), 'fe3', aqueous('fe3'), ...
    'gasH2', column('gasH2'), 'gasCO2', column('gasCO2'), ...
    'gasCH4', column('gasCH4'), 'gasH2S', column('gasH2S'), ...
    'calcite', column('calcite'), 'dolomite', column('dolomite'), ...
    'anhydrite', column('anhydrite'), 'gypsum', column('gypsum'), ...
    'goethite', column('goethite'), 'pyrite', column('pyrite'), ...
    'brucite', column('brucite'), 'portlandite', column('portlandite'));
end

function headers = normalizeHeaders(headers)
headers = cellfun(@(x) lower(regexprep(char(x), '[^a-zA-Z0-9]', '')), ...
    headers, 'UniformOutput', false);
end

function values = selectedOutputValues(raw, cellNo)
values = zeros(size(raw));
for i = 1:numel(raw)
    valueAt = raw{i};
    if ischar(valueAt) || (isstring(valueAt) && isscalar(valueAt))
        valueAt = str2double(valueAt);
    end
    if ~isnumeric(valueAt) || ~isscalar(valueAt)
        error('H2Biochem:SequentialCompositionalPhreeqcOutput', ...
            'PHREEQC selected output contains a nonnumeric entry in cell %d.', cellNo);
    end
    values(i) = valueAt;
end
end

function value = finalValue(values, headers, aliases, cellNo)
value = selectedValue(values, headers, aliases, cellNo);
value = value(end);
end

function values = selectedValue(values, headers, aliases, cellNo)
column = find(ismember(headers, aliases), 1);
assert(~isempty(column), ...
    ['PHREEQC selected output in cell %d is missing required compositional PHREEQC ', ...
     'column "%s". Available columns: %s'], ...
    cellNo, aliases{1}, strjoin(headers, ', '));
values = values(:, column);
end

function average = timeAverage(time, rate)
if isempty(time) || time(end) <= 0
    average = rate(end);
    return;
end
% Match H2Storage1D's selected-output integration: each reported rate is
% applied to the interval ending at that output time.
interval = [time(1); diff(time)];
average = sum(rate.*interval)./time(end);
end

function state = updateStateFromResults(model, state, opt, phase, mineral, result, waterMass, dt) %#ok<INUSD>
nc = model.G.cells.num;
rhoWater = opt.waterDensity;
result = result(:);
stateBefore = state;
inactive = ~phase.activeCells;

state.phreeqcPH = reshape([result.pH], [], 1);
state.phreeqcHCO3Molality = max(reshape([result.hco3], [], 1), 0);
state.phreeqcCO2Molality = max(reshape([result.aqCO2], [], 1), 0);
state.phreeqcTotalCarbon = max(reshape([result.totalCarbon], [], 1), 0);
state.tracerHCO3 = max(state.phreeqcTotalCarbon - state.phreeqcCO2Molality, 0).*rhoWater;
state.tracerSO4 = max(reshape([result.sulfate], [], 1), 0).*rhoWater;
state.tracerHS = max(reshape([result.sulfide], [], 1), 0).*rhoWater;
state.tracerCa = max(reshape([result.ca], [], 1), 0).*rhoWater;
state.tracerMg = max(reshape([result.mg], [], 1), 0).*rhoWater;
state.phreeqcFe2Molality = max(reshape([result.fe2], [], 1), 0);
state.phreeqcFe3Molality = max(reshape([result.fe3], [], 1), 0);
state.sequentialCompositionalPhreeqcAcetate = max(reshape([result.acetate], [], 1), 0);
% Diagnostic: the TDS PHREEQC's RATES blocks actually evaluated this call
% (RHO-based unless sequentialCompositionalPhreeqcPinTDS pins it to
% phase.brineTDS), alongside the pre-call brine-only estimate, so the two
% can be compared directly instead of assumed.
state.sequentialCompositionalPhreeqcTDS = reshape([result.tds], [], 1);
state.sequentialCompositionalPhreeqcBrineTDS = phase.brineTDS;

pka = state.phreeqcPH - log10(state.phreeqcHCO3Molality./ ...
    max(state.phreeqcCO2Molality, 1e-30));
previousPka = getStateVector(state, 'phreeqcCarbonatePka1', nc, ...
    model.carbonateBufferPka1);
pka(~isfinite(pka)) = previousPka(~isfinite(pka));
state.phreeqcCarbonatePka1 = pka;

state.phreeqcMineralCalcite = max(reshape([result.calcite], [], 1), 0).*waterMass;
state.phreeqcMineralDolomite = max(reshape([result.dolomite], [], 1), 0).*waterMass;
state.phreeqcMineralAnhydrite = max(reshape([result.anhydrite], [], 1), 0).*waterMass;
state.phreeqcMineralQuartz = max(reshape([result.quartz], [], 1), 0).*waterMass;
state.phreeqcMineralGoethite = max(reshape([result.goethite], [], 1), 0).*waterMass;
state.phreeqcMineralBrucite = max(reshape([result.brucite], [], 1), 0).*waterMass;
state.phreeqcMineralPortlandite = max(reshape([result.portlandite], [], 1), 0).*waterMass;
state.phreeqcMineralPyrite = max(reshape([result.pyrite], [], 1), 0).*waterMass;
state.phreeqcMineralGypsum = max(reshape([result.gypsum], [], 1), 0).*waterMass;

biomassMET = max(reshape([result.biomassMET], [], 1), 0);
biomassACE = max(reshape([result.biomassACE], [], 1), 0);
biomassSRB = max(reshape([result.biomassSRB], [], 1), 0);
biomassMET(inactive) = state.sequentialCompositionalPhreeqcBiomassMET(inactive);
biomassACE(inactive) = state.sequentialCompositionalPhreeqcBiomassACE(inactive);
biomassSRB(inactive) = state.sequentialCompositionalPhreeqcBiomassSRB(inactive);
state.sequentialCompositionalPhreeqcBiomassMET = biomassMET;
state.sequentialCompositionalPhreeqcBiomassACE = biomassACE;
state.sequentialCompositionalPhreeqcBiomassSRB = biomassSRB;
reactionRates = [reshape([result.rateMET], [], 1), ...
    reshape([result.rateACE], [], 1), reshape([result.rateSRB], [], 1)];
reactionRates(inactive, :) = 0;
state.sequentialCompositionalPhreeqcReactionRates = reactionRates;
state.sequentialCompositionalPhreeqcActiveCells = phase.activeCells;
state.sequentialCompositionalPhreeqcH2ConsumptionByReactionRate = reactionRates.*waterMass;
state.sequentialCompositionalPhreeqcH2ConsumptionByReactionMoles = ...
    state.sequentialCompositionalPhreeqcH2ConsumptionByReactionRate.*dt;
state.sequentialCompositionalPhreeqcH2ConsumptionRate = sum(reactionRates, 2).*waterMass;
state.sequentialCompositionalPhreeqcH2ConsumptionMoles = ...
    state.sequentialCompositionalPhreeqcH2ConsumptionRate.*dt;
state.h2ConsumptionRate = reactionRates.*waterMass;
state = restoreInactiveChemistry(state, stateBefore, inactive);

componentMoles = phase.componentMoles;
names = model.EOSModel.CompositionalMixture.names;
waterIndex = findComponent(names, {'H2O', 'Water'});
assert(~isempty(waterIndex), 'compositional PHREEQC requires the EOS H2O component.');
waterMolarMass = model.EOSModel.CompositionalMixture.molarMass(waterIndex);
componentMoles(:, waterIndex) = max(componentMoles(:, waterIndex) + ...
    (reshape([result.water], [], 1) - 1).*waterMass./waterMolarMass, 0);
componentMoles = replaceComponentMoles(componentMoles, names, {'H2', 'Hydrogen'}, ...
    (reshape([result.gasH2], [], 1) + reshape([result.aqH2], [], 1)).*waterMass, true);
componentMoles = replaceComponentMoles(componentMoles, names, {'CO2', 'CarbonDioxide'}, ...
    (reshape([result.gasCO2], [], 1) + reshape([result.aqCO2], [], 1)).*waterMass, true);
componentMoles = replaceComponentMoles(componentMoles, names, {'C1', 'CH4', 'Methane'}, ...
    (reshape([result.gasCH4], [], 1) + reshape([result.aqCH4], [], 1)).*waterMass, true);
componentMoles = replaceComponentMoles(componentMoles, names, {'H2S', 'HydrogenSulfide'}, ...
    reshape([result.gasH2S], [], 1).*waterMass, true);
componentMoles = replaceComponentMoles(componentMoles, names, {'N2', 'Nitrogen'}, ...
    (reshape([result.gasN2], [], 1) + reshape([result.aqN2], [], 1)).*waterMass, false);
componentMoles = replaceComponentMoles(componentMoles, names, ...
    {'CH3COOH', 'AceticAcid', 'Acetate'}, ...
    max(reshape([result.acetate], [], 1), 0).*waterMass, false);
componentMoles(inactive, :) = phase.componentMoles(inactive, :);
assert(all(isfinite(componentMoles(:)) & componentMoles(:) >= 0), ...
    'compositional PHREEQC returned invalid EOS component inventories.');

totalMoles = sum(componentMoles, 2);
assert(all(isfinite(totalMoles) & totalMoles > 0), ...
    'compositional PHREEQC produced invalid total EOS inventory.');
state.components = bsxfun(@rdivide, componentMoles, totalMoles);
assert(all(abs(sum(state.components, 2) - 1) < 100*eps), ...
    'compositional PHREEQC produced EOS compositions that do not sum to one.');

state = clearStateFunctionCaches(model, state);
model = updateEOSSalinityForReflash(model, state);
state = model.computeFlash(state, inf);
state = refreshOutputStateFunctions(model, state);
end

function state = restoreInactiveChemistry(state, stateBefore, inactive)
fields = {'phreeqcPH', 'phreeqcHCO3Molality', 'phreeqcCO2Molality', ...
    'phreeqcTotalCarbon', 'tracerHCO3', 'tracerSO4', 'tracerHS', ...
    'tracerCa', 'tracerMg', 'phreeqcFe2Molality', 'phreeqcFe3Molality', ...
    'sequentialCompositionalPhreeqcAcetate', 'phreeqcCarbonatePka1', ...
    'phreeqcMineralCalcite', 'phreeqcMineralDolomite', ...
    'phreeqcMineralAnhydrite', 'phreeqcMineralQuartz', ...
    'phreeqcMineralGoethite', 'phreeqcMineralBrucite', ...
    'phreeqcMineralPortlandite', 'phreeqcMineralPyrite', ...
    'phreeqcMineralGypsum'};
for i = 1:numel(fields)
    field = fields{i};
    if isfield(stateBefore, field)
        state.(field)(inactive, :) = stateBefore.(field)(inactive, :);
    end
end
end

function componentMoles = replaceComponentMoles(componentMoles, names, aliases, values, required)
index = findComponent(names, aliases);
if isempty(index)
    assert(~required, 'compositional PHREEQC requires EOS component %s.', aliases{1});
    return;
end
componentMoles(:, index) = max(values, 0);
end

function [rhoL, rhoV, sL, sV] = getPhaseProperties(model, state)
nc = model.G.cells.num;
s = value(state.s);
liquid = model.getLiquidIndex();
vapor = model.getVaporIndex();
if iscell(s)
    sL = s{liquid};
    sV = s{vapor};
else
    sL = s(:, liquid);
    sV = s(:, vapor);
end
propmodel = model.EOSModel.PropertyModel;
rhoL = propmodel.computeMolarDensity(model.EOSModel, value(state.pressure), ...
    value(state.x), value(state.Z_L), value(state.T), true);
rhoV = propmodel.computeMolarDensity(model.EOSModel, value(state.pressure), ...
    value(state.y), value(state.Z_V), value(state.T), false);
rhoL = asCellVector(value(rhoL), nc, 'liquid molar density');
rhoV = asCellVector(value(rhoV), nc, 'gas molar density');
sL = asCellVector(sL, nc, 'liquid saturation');
sV = asCellVector(sV, nc, 'gas saturation');
end

function componentMoles = getEOSComponentMoles(model, state)
nc = model.G.cells.num;
poreVolume = asCellVector(value(model.PVTPropertyFunctions.get( ...
    model, state, 'PoreVolume')), nc, 'pore volume');
[rhoL, rhoV, sL, sV] = getPhaseProperties(model, state);
totalMoles = poreVolume.*(sL.*rhoL + sV.*rhoV);
assert(all(isfinite(totalMoles) & totalMoles > 0), ...
    'compositional PHREEQC coupling requires positive EOS moles per cell.');
components = value(state.components);
assert(ismatrix(components) && size(components, 1) == nc && ...
    size(components, 2) == model.EOSModel.getNumberOfComponents(), ...
    'EOS components must be a cell-by-component matrix.');
componentMoles = bsxfun(@times, totalMoles, components);
end

function [x, rhoMolarL] = getLiquidCompositionAndDensity(model, state)
x = value(state.x);
if iscell(x)
    x = horzcat(x{:});
end
rhoMolarL = model.EOSModel.PropertyModel.computeMolarDensity(model.EOSModel, ...
    value(state.pressure), value(state.x), value(state.Z_L), value(state.T), true);
rhoMolarL = value(rhoMolarL);
end

function moles = getComponentMoles(componentMoles, names, aliases, required)
if nargin < 4
    required = true;
end
index = findComponent(names, aliases);
if isempty(index)
    assert(~required, 'compositional PHREEQC requires EOS component %s.', aliases{1});
    moles = zeros(size(componentMoles, 1), 1);
    return;
end
moles = componentMoles(:, index);
end

function moles = zeroTraceComponent(moles, components, names, aliases)
index = findComponent(names, aliases);
if ~isempty(index)
    moles(components(:, index) <= 1e-8) = 0;
end
end

function pressure = gasPartialPressure(moles, phase)
% compositional PHREEQC supplies PHREEQC with p_i = Z_v*n_i*R*T/V_g (atm).
pressure = phase.ZV.*moles.*0.082057366080960.*phase.gasTemperature./ ...
    phase.gasVolumeL;
end

function state = clearStateFunctionCaches(model, state)
groups = model.getStateFunctionGroupings();
for i = 1:numel(groups)
    name = groups{i}.getStateFunctionContainerName();
    if isfield(state, name)
        state = rmfield(state, name);
    end
end
end

function state = refreshOutputStateFunctions(model, state)
outputs = unique(model.OutputStateFunctions, 'stable');
for i = 1:numel(outputs)
    [~, state] = model.getProp(state, outputs{i});
end
end

function model = updateEOSSalinityForReflash(model, state)
if model.sulfateReduction && isa(model.EOSModel, 'SoreideWhitsonEos')
    assert(isfield(state, 'tracerHS') && isfield(state, 'h2sDissolvedLag'), ...
        'compositional PHREEQC reflash requires HS and lagged dissolved-H2S state.');
    model.EOSModel = model.EOSModel.enablesrb_coupling( ...
        value(state.tracerSO4), value(state.tracerHS), ...
        value(state.tracerHS) + value(state.h2sDissolvedLag), value(state.T));
end
end

function waterMass = getWaterMass(model, state, rhoWater) %#ok<INUSD>
poreVolume = value(model.PVTPropertyFunctions.get(model, state, 'PoreVolume'));
s = value(state.s);
liquid = model.getLiquidIndex();
if iscell(s)
    sL = s{liquid};
else
    sL = s(:, liquid);
end
names = model.EOSModel.CompositionalMixture.names;
waterIndex = findComponent(names, {'H2O', 'Water'});
assert(~isempty(waterIndex), 'compositional PHREEQC requires an EOS H2O component.');
[x, rhoMolarL] = getLiquidCompositionAndDensity(model, state);
waterMass = poreVolume.*max(sL, 1e-12).*rhoMolarL.* ...
    max(x(:, waterIndex), 0).*model.EOSModel.CompositionalMixture.molarMass(waterIndex);
assert(all(isfinite(waterMass) & waterMass > 0), ...
    'compositional PHREEQC coupling requires positive liquid water mass.');
end

function values = getStateVector(state, field, nc, default)
if isfield(state, field)
    values = value(state.(field));
else
    values = default;
end
values = asCellVector(values, nc, field);
end

function values = optionVector(options, field, default, nc)
if isfield(options, field)
    values = options.(field);
else
    values = default;
end
values = asCellVector(values, nc, field);
end

function values = asCellVector(values, nc, name)
if isscalar(values)
    values = repmat(values, nc, 1);
else
    values = values(:);
    assert(numel(values) == nc, ...
        'compositional PHREEQC expected %d %s values, got %d.', nc, name, numel(values));
end
end

function index = findComponent(names, aliases)
index = [];
for i = 1:numel(aliases)
    index = find(strcmpi(names, aliases{i}), 1);
    if ~isempty(index)
        return;
    end
end
end

function result = emptyResult()
result = struct( ...
    'pH', 0, 'aqH2', 0, 'aqN2', 0, 'aqCO2', 0, 'aqCH4', 0, 'aqH2S', 0, ...
    'water', 0, 'gasH2', 0, 'gasCO2', 0, 'gasCH4', 0, 'gasH2S', 0, ...
    'gasN2', 0, 'calcite', 0, 'anhydrite', 0, 'gypsum', 0, 'dolomite', 0, ...
    'goethite', 0, 'pyrite', 0, 'brucite', 0, 'portlandite', 0, 'quartz', 0, ...
    'biomassSRB', 0, 'biomassMET', 0, 'biomassACE', 0, 'totalCarbon', 0, ...
    'sulfate', 0, 'ca', 0, 'mg', 0, 'acetate', 0, 'sulfide', 0, 'hco3', 0, ...
    'fe2', 0, 'fe3', 0, 'initialSystemHydrogen', 0, 'systemHydrogen', 0, ...
    'rateMET', 0, 'rateACE', 0, 'rateSRB', 0, 'tds', 0);
end

function isAbsolute = isAbsolutePath(path)
path = char(path);
isAbsolute = ~isempty(regexp(path, '^[A-Za-z]:[\\/]|^\\\\', 'once')) || ...
    startsWith(path, filesep);
end
